import type { LucideIcon } from "lucide-react-dash";
import { Clock3, Inbox, Mail, MessageCircle, Phone, Send, Star, User } from "lucide-react-dash";

export type Conversation = {
  id: number;
  group: "Pinned" | "Today" | "Yesterday";
  name: string;
  subject: string;
  preview: string;
  time: string;
  isUnread: boolean;
  isOnline: boolean;
  unreadCount: number;
  contact: Contact;
  messages: Message[];
};

export type Message = {
  id: number;
  align: "start" | "end";
  text: string;
  time: string;
  reaction?: string;
};

export type Contact = {
  name: string;
  role: string;
  company: string;
  email: string;
  phone: string;
  website: string;
  location: string;
  timezone: string;
  status: string;
  qualifiedAt: string;
  tags: string[];
};

export type NavItem = {
  id: string;
  title: string;
  label?: string;
  icon: LucideIcon;
  isActive: boolean;
};

export const navItems: NavItem[] = [
  { id: "inbox", title: "Inbox", label: "12", icon: Inbox, isActive: true },
  { id: "mentions", title: "Mentions", label: "2", icon: Mail, isActive: false },
  { id: "snoozed", title: "Snoozed", icon: Clock3, isActive: false },
  { id: "sent", title: "Sent", icon: Send, isActive: false },
  { id: "all", title: "All conversations", icon: MessageCircle, isActive: false },
  { id: "unassigned", title: "Unassigned", label: "3", icon: User, isActive: false },
];

export const channelItems: NavItem[] = [
  { id: "email", title: "Email", label: "6", icon: Mail, isActive: false },
  { id: "chat", title: "Chat", label: "12", icon: MessageCircle, isActive: false },
  { id: "whatsapp", title: "WhatsApp", label: "0", icon: Phone, isActive: false },
  { id: "instagram", title: "Instagram", label: "0", icon: Phone, isActive: false },
  { id: "facebook", title: "Facebook", label: "0", icon: Phone, isActive: false },
  { id: "phone", title: "Phone", label: "0", icon: Phone, isActive: false },
];

export const viewItems: NavItem[] = [
  { id: "vip", title: "Flagship Projects", label: "4", icon: Star, isActive: false },
  { id: "orders", title: "Kostencheck Reviews", label: "6", icon: Inbox, isActive: false },
  { id: "feedback", title: "Project Memory Queries", label: "5", icon: MessageCircle, isActive: false },
];

export const conversations: Conversation[] = [
  // Pinned
  {
    id: 1,
    group: "Pinned",
    name: "Kostencheck Copilot",
    subject: "Hatten wir schon mal ein ähnliches Projekt mit Torquemotor?",
    preview:
      "Ja — Weiss Fertigungstechnik 2023 und die aktuelle Bergmann-Bestellung teilen sich den TM-75 mit 14 Wochen Lieferzeit.",
    time: "Just now",
    isUnread: true,
    isOnline: true,
    unreadCount: 3,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Bergmann", "Projektgedächtnis"],
    },
    messages: [
      {
        id: 101,
        align: "end",
        text: "Hatten wir schon mal ein ähnliches Projekt mit Torquemotor?",
        time: "2 min ago",
      },
      {
        id: 102,
        align: "start",
        text: "Ja, zwei relevante Treffer im Projektgedächtnis: \"Weiss Fertigungstechnik – Torquemotor-Umrüstung 2023\" (TM-75, 14 Wochen Lieferzeit war projektkritisch) und \"Bergmann Maschinenbau – Prototypenlinie 2023\" (Vorprojekt zum aktuellen CNC-Paket, gleicher Kunde, Sondermotor-Lieferzeit war damals schon Risiko Nr. 1).",
        time: "1 min ago",
      },
      {
        id: 103,
        align: "end",
        text: "Passt genau — im aktuellen KickOff-Brief steht auch der TM-75 mit 14 Wochen Lieferzeit. Ist das Muster bekannt?",
        time: "1 min ago",
      },
      {
        id: 104,
        align: "start",
        text: "Ja, das ist ein wiederkehrendes Risiko bei Sondermotoren dieses Typs. Empfehlung: Einkauf schon vor KickOff 1 informieren, wie im aktuellen Bergmann-Fall bereits vorgesehen.",
        time: "40 sec ago",
        reaction: "👍",
      },
      {
        id: 105,
        align: "end",
        text: "Danke, das übernehme ich gleich in den Bericht an den PTL.",
        time: "10 sec ago",
        reaction: "🙏",
      },
    ],
  },
  {
    id: 2,
    group: "Pinned",
    name: "Kostencheck Copilot",
    subject: "Muster bei Bergmann und Zahlungskonditionen?",
    preview: "Gab es bei Bergmann schon öfter stille Änderungen bei den Zahlungszielen?",
    time: "5m",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Bergmann", "Zahlungskonditionen"],
    },
    messages: [
      {
        id: 201,
        align: "end",
        text: "Der Kostencheck hat bei B-88431 eine stille Änderung des Zahlungsziels von 30 auf 60 Tage gefunden. Gab es das bei Bergmann schon mal?",
        time: "5 min ago",
      },
      {
        id: 202,
        align: "start",
        text: "Direkt keine identische Abweichung, aber \"Bergmann Maschinenbau – Wartungsvertrag 2022\" vermerkt, dass der Kunde tendenziell spät zahlt. Zusätzlich zeigt \"Dresdner Maschinenfabrik – Komplettpaket 2024\" ein ähnliches Muster bei einem vergleichbaren Auftragsvolumen, dort waren Zahlungskonditionen ebenfalls strittig.",
        time: "4 min ago",
      },
      {
        id: 203,
        align: "end",
        text: "Gut zu wissen, dann eskaliere ich das direkt an die Freigabe-Prüfung.",
        time: "3 min ago",
      },
      {
        id: 204,
        align: "start",
        text: "Empfehlung notiert: Position im Abweichungsbericht als 'niedrige Konfidenz — bitte prüfen' markiert, da sie nur im Fließtext stand statt in der strukturierten Tabelle.",
        time: "2 min ago",
        reaction: "✅",
      },
    ],
  },
  {
    id: 3,
    group: "Pinned",
    name: "Kostencheck Copilot",
    subject: "Reitstock-Ersatzartikel — Präzedenzfall gesucht",
    preview: "Brauche einen Präzedenzfall für die Klassifizierung von Reitstock-Ersatzartikeln.",
    time: "8m",
    isUnread: true,
    isOnline: false,
    unreadCount: 2,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Reitstock", "Ersatzartikel"],
    },
    messages: [
      {
        id: 301,
        align: "end",
        text: "Für den RS-100 zu RS-90 Ersatz bei Bergmann brauche ich einen Präzedenzfall zur Klassifizierung.",
        time: "8 min ago",
      },
      {
        id: 302,
        align: "start",
        text: "\"Trautmann Feinmechanik – Reitstock-Austausch 2023\" ist der Präzedenzfall für die heutige Ersatzartikel-Klassifizierung. Zusätzlich zeigt \"Keller Präzision – Reitstock-Sonderanfertigung 2023\", dass individuelle RS-90-Konstruktionen bereits erfolgreich freigegeben wurden.",
        time: "7 min ago",
      },
      {
        id: 303,
        align: "end",
        text: "Perfekt, dann ist RS-90 technisch kein Neuland. Ich vermerke das für die PTL-Prüfung.",
        time: "5 min ago",
      },
      {
        id: 304,
        align: "start",
        text: "Zur Sicherheit: Kostendifferenz beim aktuellen Fall beträgt -900 €, im Trautmann-Fall war die Differenz vergleichbar gering. Freigabe-Risiko wird als niedrig eingeschätzt.",
        time: "3 min ago",
        reaction: "👍",
      },
    ],
  },
  // Today
  {
    id: 5,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Steuerungsverkabelung fehlt — schon mal vorgekommen?",
    preview: "Ist eine fehlende Steuerungsverkabelung in einer Kundenbestellung schon mal aufgefallen?",
    time: "10:42 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 4,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Steuerungsverkabelung"],
    },
    messages: [
      {
        id: 501,
        align: "end",
        text: "Ist eine fehlende Steuerungsverkabelung in einer Kundenbestellung schon mal aufgefallen?",
        time: "10:42 AM",
      },
      {
        id: 502,
        align: "start",
        text: "Ja: \"Nordmann Anlagenbau – Steuerungsverkabelung Rahmenvertrag 2024\" beschreibt genau diesen Fall — eine fehlende Position wurde früh erkannt, bevor sie zum Kostenproblem wurde.",
        time: "10:44 AM",
      },
      {
        id: 503,
        align: "end",
        text: "Beim aktuellen Fall B-88431 macht das -2.100 € aus. Wie wurde es bei Nordmann gelöst?",
        time: "10:47 AM",
      },
      {
        id: 504,
        align: "start",
        text: "Dort wurde die fehlende Position im Rahmenvertrag nachträglich per Zusatzposition ergänzt, ohne den Liefertermin zu verschieben. Ähnliches Vorgehen wird für B-88431 empfohlen.",
        time: "10:49 AM",
        reaction: "👍",
      },
      { id: 505, align: "end", text: "Danke, das reiche ich an den PTL weiter.", time: "10:50 AM" },
    ],
  },
  {
    id: 6,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Mengenabweichung Spannsystem — Muster bei Bergmann?",
    preview: "Die Menge beim Spannsystem SP-200 wurde erhöht. Ist das bei diesem Kunden schon vorgekommen?",
    time: "10:15 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Spannsystem"],
    },
    messages: [
      {
        id: 601,
        align: "end",
        text: "Die Menge beim Spannsystem SP-200 wurde von 4 auf 5 erhöht (+1.250 €). Ist das bei Bergmann schon mal vorgekommen?",
        time: "10:15 AM",
      },
      {
        id: 602,
        align: "start",
        text: "Ja, \"Bergmann Maschinenbau – Spannsystem-Nachbestellung 2021\" zeigt, dass Mengenabweichungen bereits damals ein wiederkehrendes Muster bei diesem Kunden waren.",
        time: "10:12 AM",
      },
      {
        id: 603,
        align: "end",
        text: "Gibt es auch ein Beispiel, wie sowas außerhalb von Bergmann gelöst wurde?",
        time: "10:09 AM",
      },
      {
        id: 604,
        align: "start",
        text: "\"Vogel Werkzeugbau – Spannsystem-Erweiterung 2024\": eine Mengenabweichung bei SP-150 wurde per Nachtrag zum bestehenden Vertrag gelöst, ohne die Lieferkette zu unterbrechen.",
        time: "10:06 AM",
        reaction: "✅",
      },
    ],
  },
  {
    id: 7,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Liefertermin vorgezogen bei Weber — Kapazität geprüft?",
    preview: "Der Liefertermin bei Weber wurde von KW33 auf KW29 vorgezogen. Ist das machbar?",
    time: "9:58 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 1,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Weber", "Liefertermin"],
    },
    messages: [
      {
        id: 701,
        align: "end",
        text: "Der Liefertermin bei Weber Präzisionstechnik wurde von KW33 auf KW29 vorgezogen. Ist das aus der Historie heraus machbar?",
        time: "9:58 AM",
      },
      {
        id: 702,
        align: "start",
        text: "Weber Präzisionstechnik hat keine früheren Kostencheck-Vorfälle im Projektgedächtnis, das Muster ist also neu für diesen Kunden. Ähnliche vorgezogene Termine gab es beim Rundtisch-Retrofit von Hartmann Antriebstechnik 2024, dort verlief die Lieferung termingerecht ohne Abweichungen.",
        time: "9:54 AM",
      },
      {
        id: 703,
        align: "end",
        text: "Danke, dann sehe ich das Risiko als überschaubar an.",
        time: "9:50 AM",
      },
      {
        id: 704,
        align: "start",
        text: "Empfehlung: Kapazitätsprüfung mit der Fertigung trotzdem einplanen, da Weber bislang keine vorgezogenen Termine hatte.",
        time: "9:46 AM",
        reaction: "🙏",
      },
    ],
  },
  {
    id: 8,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Wie funktioniert der deterministische Diff-Ansatz?",
    preview: "Kannst du kurz erklären, wie der Kostencheck Angebot und Bestellung vergleicht?",
    time: "9:32 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Kostencheck", "Methodik"],
    },
    messages: [
      {
        id: 801,
        align: "end",
        text: "Kannst du kurz erklären, wie der Kostencheck Angebot und Bestellung vergleicht?",
        time: "9:32 AM",
      },
      {
        id: 802,
        align: "start",
        text: "Der Pipeline-Ansatz ist deterministisch: strukturierte Positionen (Menge, Preis, Artikelnummer) werden direkt verglichen, Freitextpassagen (z. B. Zahlungskonditionen) werden separat mit niedrigerer Konfidenz markiert.",
        time: "9:28 AM",
      },
      {
        id: 803,
        align: "end",
        text: "Wurde dieser Ansatz schon mal validiert, bevor er live ging?",
        time: "9:24 AM",
      },
      {
        id: 804,
        align: "start",
        text: "Ja, \"MK Anlagenbau – Pilotintegration Kostencheck 2025\" hat genau diesen deterministischen Diff-Ansatz vor dem Live-Einsatz validiert.",
        time: "9:20 AM",
        reaction: "👍",
      },
    ],
  },
  {
    id: 9,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Gibt es einen Fall ganz ohne Kostencheck-Vorfall?",
    preview: "Brauche ein Positivbeispiel für die nächste Kundenpräsentation.",
    time: "9:12 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Projektgedächtnis", "Präsentation"],
    },
    messages: [
      {
        id: 901,
        align: "end",
        text: "Brauche ein Positivbeispiel ganz ohne Kostencheck-Vorfall für die nächste Kundenpräsentation.",
        time: "9:12 AM",
      },
      {
        id: 902,
        align: "start",
        text: "\"Falk Systemtechnik – Steuerungsintegration 2022\" hatte keinerlei Kostencheck-Vorfall. Auch \"Hartmann Antriebstechnik – Rundtisch-Retrofit 2024\" verlief termingerecht ohne Abweichungen.",
        time: "9:08 AM",
      },
      {
        id: 903,
        align: "end",
        text: "Gut, dann nehme ich Hartmann als Beispiel, da es aktueller ist.",
        time: "9:04 AM",
      },
      {
        id: 904,
        align: "start",
        text: "Verstanden. Ich stelle die Kennzahlen zu diesem Projekt für die Präsentation zusammen.",
        time: "9:00 AM",
      },
    ],
  },
  {
    id: 10,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Wie viele Bergmann-Projekte liegen im Projektgedächtnis?",
    preview: "Ich will eine Kundenübersicht für Bergmann Maschinenbau erstellen.",
    time: "8:47 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Bergmann", "Kundenübersicht"],
    },
    messages: [
      {
        id: 1001,
        align: "end",
        text: "Ich will eine Kundenübersicht für Bergmann Maschinenbau erstellen. Wie viele Projekte liegen im Projektgedächtnis?",
        time: "8:47 AM",
      },
      {
        id: 1002,
        align: "start",
        text: "Vier Bergmann-Projekte sind indexiert: Prototypenlinie 2023, Wartungsvertrag 2022, Spannsystem-Nachbestellung 2021, sowie das aktuelle CNC-Paket 2026.",
        time: "8:43 AM",
      },
      {
        id: 1003,
        align: "end",
        text: "Gibt es ein wiederkehrendes Risiko über alle vier Projekte hinweg?",
        time: "8:39 AM",
      },
      {
        id: 1004,
        align: "start",
        text: "Ja, zwei Muster: Sondermotor-Lieferzeiten (seit Prototypenlinie 2023) und Mengenabweichungen (seit Spannsystem-Nachbestellung 2021). Beide tauchen auch im aktuellen CNC-Paket wieder auf.",
        time: "8:35 AM",
      },
    ],
  },
  {
    id: 11,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Freigabe-Status für RS-90 bei Bergmann",
    preview: "Können wir den Ersatzartikel RS-90 ohne weitere Rückfrage freigeben?",
    time: "8:05 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 5,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Freigabe", "Reitstock"],
    },
    messages: [
      {
        id: 1101,
        align: "end",
        text: "Können wir den Ersatzartikel RS-90 ohne weitere Rückfrage freigeben?",
        time: "8:05 AM",
      },
      {
        id: 1102,
        align: "start",
        text: "Technisch spricht laut Trautmann- und Keller-Präzedenzfällen nichts dagegen. Formal ist aber laut KickOff-Brief eine technische Vorabprüfung durch den PTL vorgesehen, bevor final freigegeben wird.",
        time: "8:01 AM",
      },
      {
        id: 1103,
        align: "end",
        text: "Also noch nicht endgültig freigeben, sondern erst nach PTL-Rückmeldung.",
        time: "7:57 AM",
      },
      {
        id: 1104,
        align: "start",
        text: "Genau, das entspricht dem Ablauf im KickOff-Brief für AL/PTL.",
        time: "7:53 AM",
        reaction: "⚡",
      },
    ],
  },
  {
    id: 12,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Retrieval-Qualität der letzten Anfragen",
    preview: "Wie zuverlässig waren die letzten Projektgedächtnis-Antworten?",
    time: "7:38 AM",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Retrieval", "Qualität"],
    },
    messages: [
      {
        id: 1201,
        align: "end",
        text: "Wie zuverlässig waren die letzten Projektgedächtnis-Antworten?",
        time: "7:38 AM",
      },
      {
        id: 1202,
        align: "start",
        text: "Die durchschnittliche Embedding-Ähnlichkeit lag diese Woche bei 92 %, die Trefferquote (Retrieval Hit Rate) bei 94 % über alle 12 indexierten Projekte.",
        time: "7:34 AM",
      },
      {
        id: 1203,
        align: "end",
        text: "Gibt es ein Projekt mit niedrigerer Ähnlichkeit?",
        time: "7:30 AM",
      },
      {
        id: 1204,
        align: "start",
        text: "\"Falk Systemtechnik – Steuerungsintegration 2022\" liegt etwas niedriger bei 88 %, da es kaum Abweichungstext enthält, an dem sich Embeddings orientieren können.",
        time: "7:26 AM",
        reaction: "✅",
      },
    ],
  },
  {
    id: 13,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Sondermotor-Lieferzeit — Einkauf informiert?",
    preview: "Ist der Einkauf schon über die 14 Wochen Lieferzeit beim TM-75 informiert?",
    time: "6:52 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Sondermotor", "Einkauf"],
    },
    messages: [
      {
        id: 1301,
        align: "end",
        text: "Ist der Einkauf schon über die 14 Wochen Lieferzeit beim TM-75 informiert?",
        time: "6:52 AM",
      },
      {
        id: 1302,
        align: "start",
        text: "Laut KickOff-Brief für AL/PTL ist das für 5 Tage vor KickOff 1 vorgesehen. Basierend auf Weiss Fertigungstechnik 2023 war das dort projektkritisch, also empfehle ich, es vorzuziehen.",
        time: "6:48 AM",
      },
      {
        id: 1303,
        align: "end",
        text: "Gute Idee, ich schicke die Info heute noch raus.",
        time: "6:44 AM",
      },
      {
        id: 1304,
        align: "start",
        text: "Verstanden, ich markiere den Punkt im KickOff-Tracking als in Bearbeitung.",
        time: "6:40 AM",
      },
    ],
  },
  {
    id: 14,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "MK Anlagenbau — Zahlungsziel im Anschreiben",
    preview: "MK hat das Zahlungsziel im Anschreiben auf 45 Tage geändert, ist das ein bekanntes Muster?",
    time: "6:10 AM",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["MK Anlagenbau", "Zahlungsziel"],
    },
    messages: [
      {
        id: 1401,
        align: "end",
        text: "MK Anlagenbau hat das Zahlungsziel im Anschreiben auf 45 Tage geändert. Ist das ein bekanntes Muster bei diesem Kunden?",
        time: "6:10 AM",
      },
      {
        id: 1402,
        align: "start",
        text: "Kein Treffer für abweichende Zahlungsziele bei MK Anlagenbau im Projektgedächtnis. Die einzige historische Referenz, \"MK Anlagenbau – Pilotintegration Kostencheck 2025\", betraf ausschließlich die Validierung der Diff-Methodik, nicht Zahlungskonditionen.",
        time: "6:06 AM",
      },
      {
        id: 1403,
        align: "end",
        text: "Dann behandle ich es als neuen Fall und schicke es zur manuellen Bestätigung.",
        time: "6:02 AM",
      },
      {
        id: 1404,
        align: "start",
        text: "Passt, das entspricht auch der Markierung im Bericht 'bitte manuell bestätigen'.",
        time: "5:58 AM",
      },
    ],
  },
  {
    id: 15,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Weber Präzisionstechnik — Vorgeschichte?",
    preview: "Gibt es überhaupt frühere Projekte mit Weber Präzisionstechnik im System?",
    time: "5:44 AM",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Weber", "Projektgedächtnis"],
    },
    messages: [
      {
        id: 1501,
        align: "end",
        text: "Gibt es überhaupt frühere Projekte mit Weber Präzisionstechnik im System?",
        time: "5:44 AM",
      },
      {
        id: 1502,
        align: "start",
        text: "Nein, im aktuellen Index sind keine früheren Weber-Projekte hinterlegt. Weber Präzisionstechnik wird aber als überwachtes Unternehmen geführt, künftige Projekte werden automatisch indexiert.",
        time: "5:40 AM",
      },
      {
        id: 1503,
        align: "end",
        text: "Gut, dann behandeln wir die Rundtisch-Nachrüstung als Referenzfall für künftige Anfragen.",
        time: "5:36 AM",
      },
      {
        id: 1504,
        align: "start",
        text: "Notiert. Sobald der Fall abgeschlossen ist, wird er automatisch ins Projektgedächtnis aufgenommen.",
        time: "5:32 AM",
      },
    ],
  },
  {
    id: 16,
    group: "Today",
    name: "Kostencheck Copilot",
    subject: "Wie hoch ist die durchschnittliche Extraktionskonfidenz?",
    preview: "Brauche die aktuelle Kennzahl für den wöchentlichen Statusbericht.",
    time: "5:18 AM",
    isUnread: true,
    isOnline: false,
    unreadCount: 3,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["KPI", "Statusbericht"],
    },
    messages: [
      {
        id: 1601,
        align: "end",
        text: "Brauche die aktuelle Kennzahl für den wöchentlichen Statusbericht: durchschnittliche Extraktionskonfidenz?",
        time: "5:18 AM",
      },
      {
        id: 1602,
        align: "start",
        text: "Aktuell 94,2 % im Schnitt über alle verarbeiteten Dokumente, bei rund 48 Sekunden Verarbeitungszeit pro Dokument.",
        time: "5:05 AM",
      },
      {
        id: 1603,
        align: "end",
        text: "Welche Abweichungsart kommt am häufigsten vor?",
        time: "4:52 AM",
      },
      {
        id: 1604,
        align: "start",
        text: "Mengenänderungen (QTY_CHANGED) liegen vorn, gefolgt von Preisänderungen (PRICE_CHANGED), fehlenden Positionen (REMOVED) und Klauseländerungen (CLAUSE_CHANGED).",
        time: "4:40 AM",
      },
    ],
  },
  // Yesterday
  {
    id: 17,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Dresdner Maschinenfabrik als Referenz für Bergmann?",
    preview: "Können wir Dresdner Maschinenfabrik als Referenzfall für Bergmann heranziehen?",
    time: "Yesterday",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Dresdner Maschinenfabrik", "Referenz"],
    },
    messages: [
      {
        id: 1701,
        align: "end",
        text: "Können wir Dresdner Maschinenfabrik als Referenzfall für die aktuelle Bergmann-Bestellung heranziehen?",
        time: "Yesterday",
      },
      {
        id: 1702,
        align: "start",
        text: "Ja, \"Dresdner Maschinenfabrik – Komplettpaket 2024\" ist strukturell analog zur aktuellen Bergmann-Bestellung, auch dort waren die Zahlungskonditionen strittig.",
        time: "Yesterday",
      },
      {
        id: 1703,
        align: "end",
        text: "Wie wurde das damals gelöst?",
        time: "Yesterday",
      },
      {
        id: 1704,
        align: "start",
        text: "Die Konditionen wurden nach Rücksprache mit dem Kunden auf den ursprünglichen Stand zurückgesetzt. Ähnliches Vorgehen wird für B-88431 vorgeschlagen.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 18,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Indexierungsstatus Projektgedächtnis",
    preview: "Sind alle 12 historischen Projekte vollständig indexiert?",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Indexierung", "Status"],
    },
    messages: [
      {
        id: 1801,
        align: "end",
        text: "Sind alle 12 historischen Projekte vollständig indexiert?",
        time: "Yesterday",
      },
      {
        id: 1802,
        align: "start",
        text: "Ja, alle 12 Projekte zeigen den Status 'Indexiert' im Projektgedächtnis, von Hartmann Antriebstechnik 2024 bis MK Anlagenbau Pilotintegration 2025.",
        time: "Yesterday",
      },
      {
        id: 1803,
        align: "end",
        text: "Gibt es Pläne, weitere Projekte nachzuindexieren?",
        time: "Yesterday",
      },
      {
        id: 1804,
        align: "start",
        text: "Sobald ein Projekt abgeschlossen ist, wird es automatisch dem Index hinzugefügt. Aktuell läuft die Verarbeitung des Bergmann CNC-Pakets 2026.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 19,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Vergleich MK Anlagenbau Pilot vs. Live-Betrieb",
    preview: "Wie hat sich die Genauigkeit seit dem MK-Anlagenbau-Pilot entwickelt?",
    time: "Yesterday",
    isUnread: true,
    isOnline: true,
    unreadCount: 1,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["MK Anlagenbau", "Pilot"],
    },
    messages: [
      {
        id: 1901,
        align: "end",
        text: "Wie hat sich die Genauigkeit seit dem MK-Anlagenbau-Pilot entwickelt?",
        time: "Yesterday",
      },
      {
        id: 1902,
        align: "start",
        text: "Seit der Pilotintegration 2025 ist die durchschnittliche Extraktionskonfidenz von 88 % auf aktuell 94,2 % gestiegen, bei gleichzeitig kürzerer Verarbeitungszeit pro Dokument.",
        time: "Yesterday",
      },
      {
        id: 1903,
        align: "end",
        text: "Sehr gut, das nehme ich in den Quartalsbericht auf.",
        time: "Yesterday",
      },
      {
        id: 1904,
        align: "start",
        text: "Ich stelle die Kennzahlen im Detail für den Bericht zusammen.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 20,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "THD als eigener überwachter Kunde?",
    preview: "Wird THD GmbH selbst auch als überwachtes Unternehmen im System geführt?",
    time: "Yesterday",
    isUnread: false,
    isOnline: false,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["THD", "Monitoring"],
    },
    messages: [
      {
        id: 2001,
        align: "end",
        text: "Wird THD GmbH selbst auch als überwachtes Unternehmen im System geführt?",
        time: "Yesterday",
      },
      {
        id: 2002,
        align: "start",
        text: "Ja, THD GmbH ist als realer vorheriger Kunde im Monitoring hinterlegt, neben Weber Präzisionstechnik GmbH und MK Anlagenbau GmbH.",
        time: "Yesterday",
      },
      {
        id: 2003,
        align: "end",
        text: "Gut, dann sind alle drei aktuell relevanten Firmen erfasst.",
        time: "Yesterday",
      },
      {
        id: 2004,
        align: "start",
        text: "Korrekt. Ich benachrichtige dich automatisch, sobald ein neues Dokument für eine der drei Firmen verarbeitet wurde.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 21,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Falk Systemtechnik — warum niedrigere Ähnlichkeit?",
    preview: "Warum liegt die Embedding-Ähnlichkeit bei Falk Systemtechnik niedriger als bei anderen?",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Falk Systemtechnik", "Retrieval"],
    },
    messages: [
      {
        id: 2101,
        align: "end",
        text: "Warum liegt die Embedding-Ähnlichkeit bei Falk Systemtechnik niedriger als bei anderen Projekten?",
        time: "Yesterday",
      },
      {
        id: 2102,
        align: "start",
        text: "Da es keinen Kostencheck-Vorfall gab, enthält die Projektzusammenfassung wenig Abweichungstext, an dem sich die Embeddings orientieren können. Die Ähnlichkeit liegt bei rund 88 % statt der üblichen 92-96 %.",
        time: "Yesterday",
      },
      {
        id: 2103,
        align: "end",
        text: "Ist das ein Problem für die Retrieval-Qualität?",
        time: "Yesterday",
      },
      {
        id: 2104,
        align: "start",
        text: "Nein, die Trefferquote bleibt stabil, da die Projektbeschreibung trotzdem eindeutig ist. Es betrifft nur die reine Ähnlichkeitskennzahl.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 22,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Alle Bergmann-Sondermotor-Fälle auflisten",
    preview: "Kannst du mir alle Fälle mit Sondermotoren bei Bergmann-Projekten auflisten?",
    time: "Yesterday",
    isUnread: true,
    isOnline: false,
    unreadCount: 5,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Bergmann", "Sondermotor"],
    },
    messages: [
      {
        id: 2201,
        align: "end",
        text: "Kannst du mir alle Fälle mit Sondermotoren bei Bergmann-Projekten auflisten?",
        time: "Yesterday",
      },
      {
        id: 2202,
        align: "start",
        text: "Im aktuellen CNC-Paket 2026 gibt es den TM-75 mit 14 Wochen Lieferzeit. Die Prototypenlinie 2023 hatte ebenfalls einen Sondermotor als Risiko Nr. 1, allerdings ohne Projektverzögerung.",
        time: "Yesterday",
      },
      {
        id: 2203,
        align: "end",
        text: "Gibt es kundenübergreifend ein ähnliches Beispiel?",
        time: "Yesterday",
      },
      {
        id: 2204,
        align: "start",
        text: "Ja, \"Weiss Fertigungstechnik – Torquemotor-Umrüstung 2023\" mit demselben TM-75-Typ und derselben 14-wöchigen Lieferzeit, dort war es ebenfalls projektkritisch.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 23,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Vogel Werkzeugbau — Nachtrag als Standardlösung?",
    preview: "Sollten wir Nachträge bei Mengenabweichungen standardmäßig vorschlagen?",
    time: "Yesterday",
    isUnread: false,
    isOnline: true,
    unreadCount: 0,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Vogel Werkzeugbau", "Nachtrag"],
    },
    messages: [
      {
        id: 2301,
        align: "end",
        text: "Sollten wir Nachträge bei Mengenabweichungen standardmäßig als Lösung vorschlagen, so wie bei Vogel Werkzeugbau?",
        time: "Yesterday",
      },
      {
        id: 2302,
        align: "start",
        text: "Das war bei \"Vogel Werkzeugbau – Spannsystem-Erweiterung 2024\" erfolgreich, ist aber kein Automatismus. Bei Bergmann empfiehlt sich wegen des wiederkehrenden Musters eher eine frühzeitige Rücksprache vor Auftragsbestätigung.",
        time: "Yesterday",
      },
      {
        id: 2303,
        align: "end",
        text: "Verstanden, dann bleibt der Nachtrag nur eine von mehreren Optionen.",
        time: "Yesterday",
      },
      {
        id: 2304,
        align: "start",
        text: "Genau. Ich hinterlege beide Optionen im Abweichungsbericht als mögliche nächste Schritte.",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 24,
    group: "Yesterday",
    name: "Kostencheck Copilot",
    subject: "Bergmann Prototypenlinie 2023 — Details anzeigen",
    preview: "Kannst du mir die Details zur Prototypenlinie 2023 von Bergmann zeigen?",
    time: "Yesterday",
    isUnread: true,
    isOnline: true,
    unreadCount: 2,
    contact: {
      name: "Kostencheck Copilot",
      role: "RAG-Assistent für Projektgedächtnis",
      company: "ClerkTree AI",
      email: "copilot@clerktree.ai",
      phone: "n/a",
      website: "clerktree.ai",
      location: "Cloud-Deployment",
      timezone: "UTC",
      status: "Aktiv",
      qualifiedAt: "4. Juli 2026",
      tags: ["Bergmann", "Prototypenlinie"],
    },
    messages: [
      {
        id: 2401,
        align: "end",
        text: "Kannst du mir die Details zur Prototypenlinie 2023 von Bergmann zeigen? Ich will sie mit dem aktuellen CNC-Paket vergleichen.",
        time: "Yesterday",
      },
      {
        id: 2402,
        align: "start",
        text: "\"Bergmann Maschinenbau – Prototypenlinie 2023\" war das Vorprojekt zum aktuellen CNC-Paket, gleicher Kunde. Die Sondermotor-Lieferzeit galt dort bereits als Risiko Nr. 1 — dasselbe Muster zeigt sich jetzt wieder beim TM-75.",
        time: "Yesterday",
      },
      {
        id: 2403,
        align: "end",
        text: "Sehr hilfreich, das bestätigt, dass wir das Thema früh genug adressiert haben.",
        time: "Yesterday",
      },
      {
        id: 2404,
        align: "start",
        text: "Genau, der KickOff-Brief für AL/PTL sieht die frühzeitige Meldung an den Einkauf bereits vor. Damit ist das Risiko diesmal proaktiv angegangen.",
        time: "Yesterday",
      },
    ],
  },
];

export const currentUser = {
  name: "Anna Berger",
  email: "anna.berger@thd-gmbh.de",
};
