export type UserStatus = "Active" | "Pending invite" | "Deactivated" | "Locked" | "Suspended";

const teamValues = [
  "Vertrieb",
  "Kalkulation",
  "Auftragsabwicklung",
  "Technik",
  "Kostencheck",
  "Compliance",
  "Einkauf",
  "Finanzen",
] as const;

export type UserTeam = (typeof teamValues)[number];

export type UserRow = {
  email: string;
  joinedDate: string;
  lastActive: number;
  name: string;
  role: string;
  status: UserStatus;
  team: UserTeam;
  workspace: string[];
};

export const users: UserRow[] = [
  {
    name: "Markus Vogel",
    email: "markus.vogel@thd-gmbh.de",
    role: "TV",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "24 Jun 2022, 9:23 AM",
    lastActive: 0,
  },
  {
    name: "Sabine Ecker",
    email: "sabine.ecker@thd-gmbh.de",
    role: "PM",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH"],
    joinedDate: "15 Mar 2021, 2:45 PM",
    lastActive: 5,
  },
  {
    name: "Florian Brandt",
    email: "florian.brandt@thd-gmbh.de",
    role: "AL",
    status: "Active",
    team: "Auftragsabwicklung",
    workspace: ["THD GmbH"],
    joinedDate: "10 Apr 2020, 11:30 AM",
    lastActive: 14 * 24 * 60,
  },
  {
    name: "Claudia Reinhardt",
    email: "claudia.reinhardt@thd-gmbh.de",
    role: "PTL",
    status: "Active",
    team: "Technik",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "28 Feb 2021, 6:15 PM",
    lastActive: 60,
  },
  {
    name: "Jonas Petersen",
    email: "jonas.petersen@thd-gmbh.de",
    role: "PTL",
    status: "Active",
    team: "Technik",
    workspace: ["THD GmbH"],
    joinedDate: "19 May 2022, 7:55 AM",
    lastActive: 2 * 60,
  },
  {
    name: "Ines Krüger",
    email: "ines.krueger@thd-gmbh.de",
    role: "TV",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH"],
    joinedDate: "03 Jan 2023, 12:05 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Thorsten Bauer",
    email: "thorsten.bauer@thd-gmbh.de",
    role: "AL",
    status: "Active",
    team: "Auftragsabwicklung",
    workspace: ["THD GmbH"],
    joinedDate: "21 Jul 2021, 8:40 PM",
    lastActive: 3 * 60,
  },
  {
    name: "Petra Lindemann",
    email: "petra.lindemann@thd-gmbh.de",
    role: "Kostencheck-Analyst",
    status: "Active",
    team: "Kostencheck",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "16 Sep 2022, 3:25 PM",
    lastActive: 6,
  },
  {
    name: "Dennis Wagner",
    email: "dennis.wagner@thd-gmbh.de",
    role: "Kostencheck-Analyst",
    status: "Active",
    team: "Kostencheck",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "04 Nov 2021, 9:50 AM",
    lastActive: 12,
  },
  {
    name: "Annette Fischer",
    email: "annette.fischer@thd-gmbh.de",
    role: "PM",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH"],
    joinedDate: "30 Dec 2022, 4:35 PM",
    lastActive: 30,
  },
  {
    name: "Holger Schmitt",
    email: "holger.schmitt@thd-gmbh.de",
    role: "AL",
    status: "Suspended",
    team: "Auftragsabwicklung",
    workspace: ["THD GmbH"],
    joinedDate: "12 Feb 2022, 10:20 AM",
    lastActive: 8 * 24 * 60,
  },
  {
    name: "Nadine Weiss",
    email: "nadine.weiss@thd-gmbh.de",
    role: "Einkauf",
    status: "Active",
    team: "Einkauf",
    workspace: ["THD GmbH"],
    joinedDate: "08 Aug 2022, 1:10 PM",
    lastActive: 24 * 60,
  },
  {
    name: "Stefan Roth",
    email: "stefan.roth@thd-gmbh.de",
    role: "Einkauf",
    status: "Pending invite",
    team: "Einkauf",
    workspace: ["THD GmbH"],
    joinedDate: "17 Jan 2023, 5:45 PM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Bianca Hofmann",
    email: "bianca.hofmann@thd-gmbh.de",
    role: "Finanzen",
    status: "Active",
    team: "Finanzen",
    workspace: ["THD GmbH"],
    joinedDate: "02 Oct 2022, 11:15 AM",
    lastActive: 45,
  },
  {
    name: "Michael Zimmer",
    email: "michael.zimmer@thd-gmbh.de",
    role: "PTL",
    status: "Active",
    team: "Technik",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "22 May 2022, 8:30 AM",
    lastActive: 10,
  },
  {
    name: "Katrin Sommer",
    email: "katrin.sommer@thd-gmbh.de",
    role: "Compliance",
    status: "Active",
    team: "Compliance",
    workspace: ["THD GmbH"],
    joinedDate: "14 Jul 2022, 6:05 PM",
    lastActive: 4 * 60,
  },
  {
    name: "Ralf Neumann",
    email: "ralf.neumann@thd-gmbh.de",
    role: "AL",
    status: "Deactivated",
    team: "Auftragsabwicklung",
    workspace: ["THD GmbH"],
    joinedDate: "26 Nov 2021, 3:40 PM",
    lastActive: 21 * 24 * 60,
  },
  {
    name: "Julia Herrmann",
    email: "julia.herrmann@thd-gmbh.de",
    role: "TV",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH"],
    joinedDate: "11 Apr 2023, 9:05 AM",
    lastActive: 18,
  },
  {
    name: "Tobias Krause",
    email: "tobias.krause@thd-gmbh.de",
    role: "Kostencheck-Analyst",
    status: "Locked",
    team: "Kostencheck",
    workspace: ["Kostencheck Copilot"],
    joinedDate: "09 Sep 2022, 12:25 PM",
    lastActive: 2 * 24 * 60,
  },
  {
    name: "Sandra Meier",
    email: "sandra.meier@thd-gmbh.de",
    role: "PM",
    status: "Active",
    team: "Vertrieb",
    workspace: ["THD GmbH", "Kostencheck Copilot"],
    joinedDate: "05 Dec 2022, 2:15 PM",
    lastActive: 0,
  },
  {
    name: "Daniel Groß",
    email: "daniel.gross@thd-gmbh.de",
    role: "Compliance",
    status: "Active",
    team: "Compliance",
    workspace: ["THD GmbH"],
    joinedDate: "18 Jun 2022, 4:50 PM",
    lastActive: 7,
  },
  {
    name: "Verena Albrecht",
    email: "verena.albrecht@thd-gmbh.de",
    role: "Finanzen",
    status: "Suspended",
    team: "Finanzen",
    workspace: ["THD GmbH"],
    joinedDate: "01 Mar 2022, 10:10 AM",
    lastActive: 30 * 24 * 60,
  },
  {
    name: "Oliver Kraft",
    email: "oliver.kraft@thd-gmbh.de",
    role: "Compliance",
    status: "Active",
    team: "Compliance",
    workspace: ["THD GmbH"],
    joinedDate: "07 Feb 2023, 7:20 PM",
    lastActive: 60,
  },
  {
    name: "Melanie Schuster",
    email: "melanie.schuster@thd-gmbh.de",
    role: "Finanzen",
    status: "Pending invite",
    team: "Finanzen",
    workspace: ["THD GmbH"],
    joinedDate: "29 Apr 2023, 11:55 AM",
    lastActive: 90 * 24 * 60,
  },
  {
    name: "Andreas Winter",
    email: "andreas.winter@bergmann-maschinenbau.de",
    role: "Kunde",
    status: "Active",
    team: "Kostencheck",
    workspace: ["Bergmann Maschinenbau GmbH"],
    joinedDate: "13 May 2026, 6:35 PM",
    lastActive: 25,
  },
];

export const filters = {
  role: [
    "All",
    "TV",
    "PM",
    "AL",
    "PTL",
    "Kostencheck-Analyst",
    "Einkauf",
    "Finanzen",
    "Compliance",
    "Kunde",
  ],
  team: ["All", ...teamValues],
  status: ["All", "Active", "Pending invite", "Deactivated", "Locked", "Suspended"],
  workspace: ["All", "THD GmbH", "Kostencheck Copilot", "Bergmann Maschinenbau GmbH"],
};

export const statusMeta: Record<UserStatus, { badgeClass: string; dotClass: string }> = {
  Active: {
    badgeClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    dotClass: "bg-emerald-500",
  },
  "Pending invite": {
    badgeClass: "border-amber-500/20 bg-amber-500/10 text-amber-600 dark:text-amber-400",
    dotClass: "bg-amber-500",
  },
  Deactivated: {
    badgeClass: "border-border bg-muted/50 text-muted-foreground",
    dotClass: "bg-muted-foreground",
  },
  Locked: {
    badgeClass: "border-destructive/20 bg-destructive/10 text-destructive",
    dotClass: "bg-destructive",
  },
  Suspended: {
    badgeClass: "border-orange-500/20 bg-orange-500/10 text-orange-600 dark:text-orange-400",
    dotClass: "bg-orange-500",
  },
};
