import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de';

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
    en: {
        // Navigation
        'nav.about': 'About',
        'nav.blog': 'Blog',
        'nav.solutions': 'Solutions',
        'nav.contact': 'Contact Us',
        'nav.bookDemo': 'Book Demo',
        'nav.seeSolutions': 'See Solutions',
        'nav.language': 'Language',

        // Landing - Hero
        'hero.revolutionizing': 'Revolutionizing',
        'hero.bpoClaims': 'BPO Claims Processing',
        'hero.description': 'Transform your claims processing workflow with AI-driven automation, intelligent callback scheduling, and real-time sentiment analysis',

        // Landing - About (Section)
        'about.future': 'Building the Future of',
        'about.opsIntel': 'Operations Intelligence',

        // Landing - Products
        'products.arborTitle': 'Arbor',
        'products.arborDesc': 'See how AI automates your business workflows in real-time',
        'products.click': 'Click',
        'products.runDemo': 'Run Demo',
        'products.seeAction': 'to see the workflow in action',
        'products.scrollPan': 'Scroll to pan • Click nodes for details',
        'products.tryArbor': 'Try Arbor',
        'products.jurisTitle': 'Juris',
        'products.tryJuris': 'Try Juris',

        // Landing - Conversation
        'conversation.title': 'Smart Calls, Smarter Agents.',

        // Landing - FAQ
        'faq.title': 'FAQ',
        'faq.title1': 'Frequently Asked',
        'faq.title2': 'Questions',
        'faq.cantFind': "Can't find what you're looking for?",
        'faq.visitOur': 'Email us at',
        'faq.contactPage': 'team@clerktree.com',

        // FAQ Items
        'faq.q1': 'How do I get started?',
        'faq.a1': "Getting started is easy! Book a demo with our team by emailing us at team@clerktree.com, and we'll schedule a personalized walkthrough. After that, we'll help you set up a trial environment tailored to your specific use case.",
        'faq.q2': 'Do you offer a free trial?',
        'faq.a2': "Yes, we offer a 14-day free trial for qualified businesses. During the trial, you'll have access to our core features and dedicated support to help you evaluate the platform.",
        'faq.q3': 'How is ClerkTree priced?',
        'faq.a3': 'We offer flexible pricing based on your volume of documents, number of users, and specific features required. Contact our sales team for a customized quote that fits your business needs.',
        'faq.q4': 'How long does implementation take?',
        'faq.a4': 'Implementation typically takes 2-4 weeks depending on your specific requirements and existing systems. We provide dedicated onboarding support and training to ensure a smooth transition.',
        'faq.q5': 'Can I integrate ClerkTree with my existing systems?',
        'faq.a5': 'Yes! ClerkTree offers REST APIs and pre-built integrations with popular business tools including Salesforce, SAP, Microsoft Dynamics, and more. Our team can also help with custom integrations.',

        // Footer
        'footer.product': 'Product',
        'footer.company': 'Company',
        'footer.contact': 'Contact',
        'footer.features': 'Features',
        'footer.smartContracts': 'Smart Contracts',
        'footer.documents': 'Documents',
        'footer.aboutUs': 'About Us',
        'footer.careers': 'Careers',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.security': 'Security & Data Handling',
        'footer.rights': 'All rights reserved.',
        'footer.legal': 'Legal',
        'footer.docs': 'Docs',
        'footer.phone': 'Phone',
        'footer.linkedin': 'LinkedIn',
        'footer.cookiePolicy': 'Cookie Policy',

        // About Page
        'about.whyTitle': 'Why We Built ClerkTree',
        'about.whyDesc1': 'Growing operations teams face a common challenge: fragmented workflows that slow them down. Document processing scattered across multiple tools, manual data entry consuming valuable time, and disconnected systems creating bottlenecks.',
        'about.whyDesc2': 'We built ClerkTree to solve this. Our platform unifies AI-powered automation with human expertise, creating a seamless workflow that reduces turnaround time by 40% while maintaining the accuracy and judgment that only humans can provide.',
        'about.missionTitle': 'Our Mission',
        'about.missionDesc': 'To empower operations teams with intelligent automation that amplifies human capabilities, transforming tedious document-heavy processes into streamlined, efficient workflows that drive business growth.',
        'about.visionTitle': 'Our Vision',
        'about.visionDesc': 'To become the operating system for modern claims and back-office operations, where AI and humans work in perfect harmony to deliver unprecedented speed, accuracy, and customer satisfaction.',
        'about.hybridTitle': 'The Hybrid Human+AI Approach',
        'about.hybridDesc': "We believe the future isn't about replacing humans with AI—it's about augmenting human intelligence with machine capabilities. Our platform is designed around this core philosophy:",
        'about.aiRepetition': 'AI Handles Repetition',
        'about.aiRepetitionDesc': 'Automated document extraction, data validation, and routine processing tasks',
        'about.humanComplexity': 'Humans Handle Complexity',
        'about.humanComplexityDesc': 'Complex decision-making, edge cases, and customer interactions requiring empathy',
        'about.handoffs': 'Seamless Handoffs',
        'about.handoffsDesc': 'Smart routing between AI and human agents based on task complexity and confidence levels',
        'about.industriesTitle': 'Industries We Serve',
        'about.ind1': 'Insurance',
        'about.ind2': 'BFSI',
        'about.ind3': 'BPO',
        'about.ind4': 'Operations',
        'about.ind5': 'Document Processing',
        'about.joinTitle': 'Join Us on This Journey',
        'about.joinDesc': "We're just getting started. Partner with us to transform your operations.",
        'about.getInTouch': 'Get in Touch',
        'about.joinTeam': 'Join Our Team',
        'about.team.kenshin': 'Kenshin Kiriyama (COO) studies Sustainable Management at TUM. Previously in sales at Affordables working with Decathlon and Sparkasse. A Deutschlandstipendium recipient, he now ensures reliable customer service and maintenance at ClerkTree, developing tailored solutions for complex client needs.',
        'about.team.animesh': 'Animesh Mishra (Founder) studies CS & ML at Shiv Nadar Institute of Eminence. Previously a Quant Research Analyst at Consult Add Services developing predictive models, he now focuses on enterprise AI orchestration at ClerkTree. He engineers autonomous agentic workflows to streamline high-throughput claims processing.',
        'about.team.krishang': 'Krishang Sharma (AI Solutions Engineer) studies CSE at Shiv Nadar Institute of Eminence and a certified grad of the Arizona State University AI in Business program. He builds production-grade ML, LLM, and RAG systems at ClerkTree. Previously, he contributed to ML engineering and research at I4C (Ministry of Home Affairs) and the Scientific Analysis Group, DRDO.',
        'about.team.shobhit': 'Shobhit Mishra (CEO) studies at TUM, focusing on sustainable data automation. Previously working on automation projects at Robotico, he now leads scalable solution building and strategic operations at ClerkTree, driving technical innovation to help businesses streamline complex workflows.',
        'about.team.urja': 'Urja Shrestha (Customer Success Manager) studies Sustainable Management and Technology at TUM in Straubing, Bavaria. At ClerkTree, she drives client engagement by optimizing product adoption and tailoring success strategies for seamless integration.',
        'about.team.sinem': 'Sinem Koc (Legal Analyst) is a law student at Johannes Gutenberg University Mainz with a focus on life science and healthcare law and strong academic results. At ClerkTree, she works as a Legal Analyst, supporting compliance, data protection, and the legal foundations required to scale AI-driven business solutions.',

        // Contact Page
        'contact.title1': "Let's Talk About",
        'contact.title2': 'Your Business',
        'contact.subtitle': 'Get in touch with our team for enterprise solutions and support',
        'contact.phone': 'Phone',
        'contact.location': 'Location',
        'contact.sendMsgTitle': 'Send us a Message',
        'contact.sendMsgDesc': "Fill out the form below and we'll get back to you within 1-2 business days.",
        'contact.successTitle': 'Message Sent!',
        'contact.successDesc': "Thank you for contacting us. We'll be in touch soon!",
        'contact.fullName': 'Full Name',
        'contact.companyName': 'Company Name',
        'contact.email': 'Business Email',
        'contact.phoneNumber': 'Phone Number',
        'contact.interest': 'Interest',
        'contact.selectInterest': 'Select your interest...',
        'contact.intEnterprise': 'Enterprise License',
        'contact.intBulk': 'Bulk Purchase',
        'contact.intCustom': 'Custom Solution',
        'contact.intOther': 'Other',
        'contact.employees': 'Number of Employees',
        'contact.selectRange': 'Select range...',
        'contact.message': 'Message',
        'contact.messagePlaceholder': 'Tell us about your needs and requirements...',
        'contact.error': 'Something went wrong. Please try again later.',
        'contact.sending': 'Sending...',
        'contact.sendButton': 'Send Message',

        // Solutions Page
        'solutions.title1': 'Built for Modern',
        'solutions.title2': 'Claims Operations',
        'solutions.subtitle': 'Transform your workflow with enterprise-grade automation, powered by cutting-edge AI technology.',
        'solutions.card1Title': 'AI-Powered Document Processing',
        'solutions.card1Desc': 'Automatically extract, classify, and validate information from claims documents using advanced machine learning models.',
        'solutions.card1Feat1': 'OCR & Data Extraction',
        'solutions.card1Feat2': 'Document Classification',
        'solutions.card1Feat3': 'Auto-validation',
        'solutions.card2Title': 'Intelligent Workflow Automation',
        'solutions.card2Desc': 'Streamline your claims process with smart routing, automated decision-making, and seamless handoffs between AI and human agents.',
        'solutions.card2Feat1': 'Smart Task Routing',
        'solutions.card2Feat2': 'Automated Approvals',
        'solutions.card2Feat3': 'Process Optimization',
        'solutions.card3Title': 'Claims Triage & Prioritization',
        'solutions.card3Desc': 'Automatically categorize and prioritize incoming claims based on urgency, complexity, and potential fraud indicators.',
        'solutions.card3Feat1': 'Urgency Detection',
        'solutions.card3Feat2': 'Complexity Analysis',
        'solutions.card3Feat3': 'Priority Scoring',
        'solutions.card4Title': 'Real-Time Status Tracking',
        'solutions.card4Desc': 'Provide complete visibility into claim status with automated updates, notifications, and comprehensive audit trails.',
        'solutions.card4Feat1': 'Live Status Updates',
        'solutions.card4Feat2': 'Automated Notifications',
        'solutions.card4Feat3': 'Full Audit Trail',
        'solutions.card5Title': 'Analytics & Reporting',
        'solutions.card5Desc': 'Gain actionable insights with comprehensive dashboards, custom reports, and predictive analytics for better decision-making.',
        'solutions.card5Feat1': 'Custom Dashboards',
        'solutions.card5Feat2': 'Predictive Analytics',
        'solutions.card5Feat3': 'Performance Metrics',
        'solutions.card6Title': 'Compliance & Security',
        'solutions.card6Desc': 'Ensure regulatory compliance with built-in security features, audit logging, and automated compliance checks.',
        'solutions.card6Feat1': 'Data Encryption',
        'solutions.card6Feat2': 'Compliance Monitoring',
        'solutions.card6Feat3': 'Access Controls',
        'solutions.ctaBadge': 'Start Your Journey',
        'solutions.ctaTitle1': 'Ready to Transform',
        'solutions.ctaTitle2': 'Your Operations?',
        'solutions.ctaDesc': 'Schedule a personalized demo to see how our AI-powered solutions can reduce turnaround time by',
        'solutions.ctaDescHighlight': '40%',
        'solutions.ctaDescEnd': 'and dramatically improve accuracy.',
        'solutions.bookDemo': 'Book a Demo',
        'solutions.contactSales': 'Contact Sales',

        // FAQ Page
        'faqPage.title1': 'Frequently Asked',
        'faqPage.title2': 'Questions',
        'faqPage.subtitle': 'Everything you need to know about ClerkTree and how we can help transform your operations',
        'faqPage.catGeneral': 'General',
        'faqPage.catProduct': 'Product',
        'faqPage.catPricing': 'Pricing',
        'faqPage.catSecurity': 'Security',
        'faqPage.catSupport': 'Support',
        'faqPage.q1': 'What is ClerkTree?',
        'faqPage.a1': 'ClerkTree is an AI-powered workflow automation platform designed for claims and back-office operations. We combine human expertise with artificial intelligence to reduce turnaround time by 40% while maintaining accuracy and quality.',
        'faqPage.q2': 'How does the Human+AI approach work?',
        'faqPage.a2': 'Our hybrid approach uses AI to handle repetitive tasks like document extraction and data validation, while humans focus on complex decision-making and edge cases. The system intelligently routes tasks between AI and human agents based on complexity and confidence levels.',
        'faqPage.q3': 'What industries do you serve?',
        'faqPage.a3': 'We primarily serve Insurance, BFSI (Banking, Financial Services, and Insurance), BPO (Business Process Outsourcing), Operations teams, and Document Processing sectors. Our platform is optimized for document-heavy workflows and claims processing.',
        'faqPage.q4': 'What kind of documents can ClerkTree process?',
        'faqPage.a4': 'ClerkTree can process a wide variety of documents including insurance claims, invoices, contracts, medical records, financial statements, and other business documents. Our AI is trained to extract relevant information accurately and efficiently.',
        'faqPage.q5': 'How long does implementation take?',
        'faqPage.a5': 'Implementation typically takes 2-4 weeks depending on your specific requirements and existing systems. We provide dedicated onboarding support and training to ensure a smooth transition.',
        'faqPage.q6': 'How is ClerkTree priced?',
        'faqPage.a6': 'We offer flexible pricing based on your volume of documents, number of users, and specific features required. Contact our sales team for a customized quote that fits your business needs.',
        'faqPage.q7': 'Do you offer a free trial?',
        'faqPage.a7': "Yes, we offer a 14-day free trial for qualified businesses. During the trial, you'll have access to our core features and dedicated support to help you evaluate the platform.",
        'faqPage.q8': 'Is my data secure with ClerkTree?',
        'faqPage.a8': 'Absolutely. We take security seriously with end-to-end encryption, SOC 2 compliance, and regular security audits. Your data is stored in secure, enterprise-grade cloud infrastructure with multiple redundancy layers.',
        'faqPage.q9': 'What compliance standards do you meet?',
        'faqPage.a9': 'ClerkTree meets industry standards including GDPR, HIPAA, SOC 2 Type II, and ISO 27001. We continuously update our compliance measures to meet evolving regulatory requirements.',
        'faqPage.q10': 'What kind of support do you provide?',
        'faqPage.a10': 'We provide 24/7 customer support via email and chat for all enterprise customers. Premium plans include dedicated account managers and phone support. We also offer comprehensive documentation and training resources.',
        'faqPage.q11': 'Can I integrate ClerkTree with my existing systems?',
        'faqPage.a11': 'Yes! ClerkTree offers REST APIs and pre-built integrations with popular business tools including Salesforce, SAP, Microsoft Dynamics, and more. Our team can also help with custom integrations.',
        'faqPage.q12': 'How do I get started?',
        'faqPage.a12': "Getting started is easy! Book a demo with our team by emailing us at team@clerktree.com, and we'll schedule a personalized walkthrough. After that, we'll help you set up a trial environment tailored to your specific use case.",
        'faqPage.stillQuestions': 'Still Have Questions?',
        'faqPage.stillDesc': 'Our team is here to help. Get in touch and we\'ll answer any questions you have.',
        'faqPage.contactUs': 'Contact Us',

        // Careers Page
        'careers.title1': 'Join the',
        'careers.title2': 'ClerkTree Team',
        'careers.subtitle': 'Help us revolutionize operations with AI-powered automation',
        'careers.linkedin': 'Check for new jobs on LinkedIn',
        'careers.or': 'OR',
        'careers.formTitle': 'Submit Your Résumé',
        'careers.formDesc': "Fill out the form below and we'll get back to you within 2-3 business days.",
        'careers.successTitle': 'Application Submitted!',
        'careers.successDesc': "We'll review your application and get back to you soon.",
        'careers.fullName': 'Full Name',
        'careers.email': 'Email Address',
        'careers.phone': 'Phone Number',
        'careers.currentPos': 'Current Position',
        'careers.experience': 'Years of Experience',
        'careers.position': 'Position Applying For',
        'careers.select': 'Select...',
        'careers.selectPos': 'Select a position...',
        'careers.pos1': 'Senior Frontend Engineer',
        'careers.pos2': 'Fullstack Engineer',
        'careers.pos3': 'Product Designer',
        'careers.other': 'Other',
        'careers.linkedinUrl': 'LinkedIn Profile URL',
        'careers.portfolio': 'Portfolio/Website',
        'careers.coverLetter': 'Cover Letter / Why do you want to join ClerkTree?',
        'careers.resume': 'Résumé',
        'careers.upload': 'Click to upload your résumé (PDF, DOC, DOCX)',
        'careers.submit': 'Submit Application',
        'careers.submitting': 'Submitting...',
        'careers.years': 'years',

        // Blog
        'blog.all': 'All',
        'blog.selectCategory': 'Select Category',

        // Header
        'header.notifications': 'Notifications',
        'header.markAllRead': 'Mark all as read',
        'header.noNotifications': 'No new notifications',

        'header.stayUpdated': 'Stay updated with your latest activities',

        // Sidebar
        'sidebar.platform': 'Platform',
        'sidebar.aiBehavior': 'Configure AI Behavior',
        'sidebar.groqAi': 'Groq AI',
        'sidebar.systemPrompt': 'System Prompt',
        'sidebar.aiVoice': 'AI Voice',
        'sidebar.contextFields': 'Context Fields',
        'sidebar.categories': 'Categories',
        'sidebar.priorityRules': 'Priority Rules',
        'sidebar.instructions': 'Instructions',
        'sidebar.saveConfig': 'Save Config',
        'sidebar.language': 'Language',

        // Invite Page
        'invite.support': 'Support',
        'invite.error': 'Invalid invite code. Please try again.',
        'invite.title': 'Access the platform',
        'invite.subtitle': "Enter your organization's invite code to access the platform",
        'invite.placeholder': 'Enter invite code',
        'invite.continue': 'Continue',
        'invite.requestAccess': 'Request Access',
        'invite.secure': 'Secure Enterprise Connection',

        // Arbor Page & Chat
        'arbor.startTitle': 'Start a Conversation',
        'arbor.startDescAsk': 'Ask questions and get intelligent answers',
        'arbor.startDescTell': 'Execute autonomous tasks and actions',
        'arbor.startDescSearch': 'Search through your documents',
        'arbor.placeholderAsk': 'Ask a question about your documents...',
        'arbor.placeholderTell': 'Tell Arbor what to do...',
        'arbor.placeholderSearch': 'Search documents...',
        'arbor.viewDetails': 'View Details',
        'arbor.statusIndexing': 'Indexing...',
        'arbor.statusIndexed': 'Indexed (147 docs)',
        'arbor.filters': 'Filters',
        'arbor.reindex': 'Re-index',
        'arbor.filterType': 'Filter by Document Type',
        'arbor.dateRange': 'Date Range',
        'arbor.to': 'to',
        'arbor.simulatedResponseAsk': "Based on the information in your documents, here's what I found: This is a simulated response. In production, this would connect to the Arbor backend API.",
        'arbor.simulatedResponseTell': 'Task executed successfully. This is a simulated response. In production, this would connect to the Arbor backend and perform the requested action.',
        'arbor.simulatedResponseDoc': 'Found relevant documents matching your query. This is a simulated response.',
        'arbor.send': 'Send',
        'arbor.clear': 'Clear',
        'arbor.modeAsk': 'Ask',
        'arbor.modeTell': 'Tell',
        'arbor.modeSearch': 'Search',

        // Bioflow Page
        'bioflow.title': 'AI Workflow Designer',
        'bioflow.subtitle': 'See how AI automates your tasks',
        'bioflow.poweredBy': 'Powered by AI',
        'bioflow.smartAuto': 'Smart Automation',
        'bioflow.realTime': 'Real-time',
        'bioflow.back': 'Back',
        'bioflow.tryIt': 'Try it out:',
        'bioflow.instruction': 'Select a use case above, then click',
        'bioflow.runWorkflow': 'Run Workflow',
        'bioflow.inAction': 'to see the AI in action',
        'bioflow.controls': 'Scroll to pan • Click nodes for details • Zoom with controls',

        // Blog Page
        'blogPage.title': 'Blog',
        'blogPage.subtitle': 'Latest news and updates from ClerkTree.',
        'blogPage.loadingArticles': 'Loading articles...',
        'blogPage.loading': 'Loading...',

        // Blog Post
        'blogPost.backToAll': 'Back to all articles',
        'blogPost.related': 'Related Articles',
        'blogPost.errorRendering': 'Error rendering content:',

        // Demo Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Dashboard',
        'dashboard.userView': 'User View',
        'dashboard.totalHistory': 'Total History',
        'dashboard.criticalHigh': 'Critical/High',
        'dashboard.avgDuration': 'Avg Duration',
        'dashboard.followUps': 'Follow-ups',
        'dashboard.active': 'active',
        'dashboard.allTime': 'All time',
        'dashboard.needAttention': 'Need attention',
        'dashboard.perCall': 'Per call',
        'dashboard.pending': 'Pending',
        'dashboard.priorityQueue': 'Priority Queue',
        'dashboard.priority.critical': 'Critical',
        'dashboard.priority.high': 'High Priority',
        'dashboard.priority.medium': 'Medium',
        'dashboard.priority.low': 'Low Priority',
        'dashboard.priority.highShort': 'High',
        'dashboard.priority.mediumShort': 'Medium',
        'dashboard.priority.lowShort': 'Low',
        'dashboard.priority.noPending': 'No pending',
        'dashboard.priority.needFollowUp': 'need follow-up',

        'dashboard.tab.monitor': 'Monitor',
        'dashboard.tab.config': 'Configuration',
        'dashboard.tab.history': 'History',
        'dashboard.tab.monitorFull': 'Live Monitor',
        'dashboard.tab.configFull': 'Knowledge Base',
        'dashboard.tab.historyFull': 'History',

        'dashboard.footer': 'ClerkTree AI Dashboard',

        // Documents Page
        'documents.adminTitle': 'Admin Document Review',
        'documents.searchPlaceholder': 'Search by ticket ID or name...',
        'documents.statusAll': 'Status: All',
        'documents.priorityAll': 'Priority: All',
        'documents.status.pending': 'Pending',
        'documents.status.verified': 'Verified',
        'documents.status.rejected': 'Rejected',
        'documents.priority.high': 'High',
        'documents.priority.medium': 'Medium',
        'documents.priority.low': 'Low',

        'documents.statistics': 'Statistics',
        'documents.stats.pending': 'Clients Pending Review',
        'documents.stats.verified': 'Clients Verified',
        'documents.stats.progress': 'Review Progress',
        'documents.stats.complete': 'Complete',
        'documents.stats.clients': 'Clients',

        'documents.quickActions': 'Quick Actions',
        'documents.exportReports': 'Export Reports',

        'documents.ticket': 'Ticket:',
        'documents.type': 'Type:',
        'documents.uploadedDocs': 'Uploaded Documents',

        'documents.blockchain.details': 'Blockchain Details',
        'documents.blockchain.hash': 'Document Hash:',
        'documents.blockchain.status': 'Status:',
        'documents.blockchain.uploader': 'Uploader:',
        'documents.blockchain.uploadTime': 'Upload Time:',
        'documents.blockchain.verifier': 'Verifier:',
        'documents.blockchain.verificationTime': 'Verification Time:',
        'documents.blockchain.verified': 'Verified',
        'documents.blockchain.pending': 'Pending Verification',
        'documents.blockchain.refresh': 'Click the refresh button to load blockchain data',

        'documents.preview.notAvailable': 'Preview not available for {ext} files',

        'documents.modal.submissionDate': 'Submission Date',
        'documents.modal.status': 'Status',
        'documents.modal.preview': 'Document Preview',
        'documents.modal.details': 'Document Details',
        'documents.modal.client': 'Client:',
        'documents.modal.ticketId': 'Ticket ID:',
        'documents.modal.docType': 'Document Type:',
        'documents.modal.history': 'Review History',
        'documents.modal.noHistory': 'No review history available',

        // User Call & Chat
        'userCall.aiAssistant': 'Chat',
        'userCall.settings': 'Settings',
        'chat.welcome': 'How can I help you today?',
        'chat.startPrompt': 'Type a message or start a voice call to begin your conversation',
        'chat.thought': 'Thought for {time}s',
        'chat.listening': 'Listening...',
        'chat.placeholder.voice': 'Or type a message...',
        'chat.placeholder.text': 'Type your message...',
        'chat.end': 'End',
        'chat.agentError': 'Sorry, I encountered an error. Please try again.',

        // Juris Page & Chat
        'juris.caseConnection': 'Case Connection Analysis',
        'juris.close': 'Close',
        'juris.selectedCase': 'Selected Case',
        'juris.connectsToQuery': 'How it connects to your query:',
        'juris.legalConcepts': 'Legal Concepts:',
        'juris.precedentChain': 'Precedent Chain:',
        'juris.similarityScore': 'Similarity Score:',
        'juris.citedStatutes': 'Cited Statutes:',
        'juris.retrievalTitle': 'Legal Case Retrieval',
        'juris.descNormal': 'Fast semantic search using AI embeddings',
        'juris.descDeep': 'Comprehensive analysis with citation networks and precedents',
        'juris.detailNormal': 'Quick results using vector similarity',
        'juris.detailDeep': 'Combines semantic search, knowledge graph, and citations',
        'juris.foundSimilar': 'Found Similar Cases',
        'juris.aiAnalysis': 'AI Analysis',
        'juris.summary': 'Summary:',
        'juris.keyConcepts': 'Key Concepts:',
        'juris.tryExamples': 'Try these examples:',
        'juris.placeholderNormal': 'Search cases by legal concepts, facts, or holdings...',
        'juris.placeholderDeep': 'Ask complex legal questions requiring deep analysis...',
        'juris.placeholderClear': 'Clear chat to start a new search...',
        'juris.modeNormal': 'Normal',
        'juris.modeDeep': 'Deep Search',
        'juris.simulatedDeep': "Based on your detailed query, I have conducted a comprehensive analysis of the relevant legal precedents and statutory provisions.\n\nThe search has identified {count} highly significant cases that directly address the legal issues you've raised. The analysis suggests a strong precedential trend favoring the interpretation of specific statutory clauses in line with recent Supreme Court judgments.\n\nKey findings include:\n1. A consistent judicial approach towards protecting fundamental rights in similar contexts.\n2. Divergent views in High Court rulings which have been settled by the Apex Court.\n3. Specific reliance on procedural adherence as a critical factor in case outcomes.\n\nBelow are the most relevant cases with detailed citation networks and reasoning patterns for your review.",
        'juris.simulatedNormal': 'I found {count} relevant cases for your situation. These cases cover similar scenarios and can help you understand the potential legal outcomes.',

        // LiveCallMonitor
        'monitor.title': 'Live Monitor',
        'monitor.status.active': 'Active',
        'monitor.status.idle': 'Idle',
        'monitor.apptDetails': 'Appointment Details',
        'monitor.contactInfo': 'Contact Info',
        'monitor.noContact': 'No contact yet',
        'monitor.otherDetails': 'Other Details',
        'monitor.category': 'Category:',
        'monitor.noActive': 'No Active Conversation',
        'monitor.waiting': 'Waiting for conversation...',
        'monitor.startCall': 'Start a call to see transcript',
        'monitor.recording': 'Recording & analyzing conversation...',
        'monitor.recordingShort': 'Recording...',
        'monitor.followUp': 'Follow-up needed',

        // KnowledgeBase (Config)
        'config.title': 'Knowledge Base',
        'config.subtitle': 'Configure AI behavior',
        'config.save': 'Save Config',
        'config.saved': 'Saved!',
        'config.systemPrompt': 'System Prompt',
        'config.systemPromptDesc': "Define the AI's core behavior and personality...",
        'config.persona': 'AI Persona',
        'config.personaPlaceholder': 'e.g., Professional, empathetic, and efficient assistant',
        'config.greeting': 'Opening Greeting',
        'config.greetingPlaceholder': 'How the AI greets callers...',
        'config.guidelines': 'Response Guidelines',
        'config.guidelinesPlaceholder': 'Guidelines for how the AI should respond...',
        'config.voice': 'AI Voice',
        'config.fields': 'Context Fields',
        'config.fieldsDesc': 'Define fields the AI should extract from conversations',
        'config.categories': 'Categories',
        'config.categoriesDesc': 'Categories for call classification',
        'config.rules': 'Priority Rules',
        'config.instructions': 'Instructions',
        'config.addField': 'Add Field',
        'config.addCategory': 'Add Category',
        'config.fieldName': 'Field name',
        'config.fieldDesc': 'Description (optional)',
        'config.required': 'Required field',
        'config.cancel': 'Cancel',
        'config.add': 'Add',
        'config.catName': 'Category name',
        'config.catDesc': 'Description',
        'config.groqConnected': 'Groq',
        'config.groqOffline': 'Offline',

        // CallHistory
        'history.title': 'History',
        'history.stats': '{count} of {total} items • {voice} calls, {text} chats',
        'history.justNow': 'Just now',
        'history.ago.h': '{h}h ago',
        'history.ago.d': '{d}d ago',
        'history.duration': '{m}m {s}s',
        'history.noHistory': 'No History Found',
        'history.noHistoryDesc': 'Call and chat history will appear here',
        'history.adjustFilters': 'Try adjusting your filters',
        'history.filter.allTypes': 'All Types',
        'history.filter.calls': 'Calls Only',
        'history.filter.chats': 'Chats Only',
        'history.filter.allPriorities': 'All Priorities',
        'history.filter.allCategories': 'All Categories',
        'history.type.call': 'Call',
        'history.type.chat': 'Chat',
        'history.intent': 'Caller Intent',
        'history.sentiment': 'Sentiment',
        'history.priority': 'Priority',
        'history.resolution': 'Resolution',
        'history.riskLevel': 'Risk Level',
        'history.noTranscript': 'No transcript available',
        'history.keyPoints': 'Key Points',
        'history.topics': 'Topics',
        'history.mood': 'Mood Indicators',
        'history.suggestions': 'AI Suggestions for Admin',
        'history.actionItems': 'Action Items',
        'history.extractedInfo': 'Extracted Information',
        'history.tags': 'Tags',

        // Active Sessions Panel
        'dashboard.activeSessions': 'Active Sessions',
        'dashboard.voiceCalls': 'Voice Calls',
        'dashboard.textChats': 'Text Chats',
        'dashboard.inProgress': 'In progress',
        'dashboard.noActive': 'No active sessions',
    },
    de: {
        // Navigation
        'nav.about': 'Über uns',
        'nav.blog': 'Blog',
        'nav.solutions': 'Lösungen',
        'nav.contact': 'Kontaktieren Sie uns',
        'nav.bookDemo': 'Demo buchen',
        'nav.seeSolutions': 'Lösungen ansehen',
        'nav.language': 'Sprache',

        // Landing - Hero
        'hero.revolutionizing': 'Revolutionierung der',
        'hero.bpoClaims': 'BPO-Schadensbearbeitung',
        'hero.description': 'Transformieren Sie Ihren Workflow zur Schadensbearbeitung mit KI-gesteuerter Automatisierung, intelligenter Rückrufplanung und Echtzeit-Stimmungsanalyse',

        // Landing - About
        'about.future': 'Die Zukunft der',
        'about.opsIntel': 'Operations Intelligence gestalten',

        // Landing - Products
        'products.arborTitle': 'Arbor',
        'products.arborDesc': 'Erleben Sie, wie KI Ihre Geschäftsabläufe in Echtzeit automatisiert',
        'products.click': 'Klicken Sie auf',
        'products.runDemo': 'Demo starten',
        'products.seeAction': 'um den Workflow in Aktion zu sehen',
        'products.scrollPan': 'Scrollen zum Schwenken • Klicken für Details',
        'products.tryArbor': 'Arbor testen',
        'products.jurisTitle': 'Juris',
        'products.tryJuris': 'Juris testen',

        // Landing - Conversation
        'conversation.title': 'Smarte Anrufe, Klügere Agenten.',

        // Landing - FAQ
        'faq.title': 'FAQ',
        'faq.title1': 'Häufig gestellte',
        'faq.title2': 'Fragen',
        'faq.cantFind': 'Nicht gefunden, was Sie suchen?',
        'faq.visitOur': 'Schreiben Sie uns an',
        'faq.contactPage': 'team@clerktree.com',

        // FAQ Items
        'faq.q1': 'Wie fange ich an?',
        'faq.a1': 'Der Einstieg ist einfach! Buchen Sie eine Demo, indem Sie uns eine E-Mail an team@clerktree.com senden, und wir vereinbaren einen persönlichen Durchgang. Danach helfen wir Ihnen, eine Testumgebung einzurichten, die auf Ihren spezifischen Anwendungsfall zugeschnitten ist.',
        'faq.q2': 'Bieten Sie eine kostenlose Testphase an?',
        'faq.a2': 'Ja, wir bieten eine 14-tägige kostenlose Testphase für qualifizierte Unternehmen an. Während der Testphase haben Sie Zugriff auf unsere Kernfunktionen und engagierten Support, um die Plattform zu evaluieren.',
        'faq.q3': 'Wie ist die Preisgestaltung von ClerkTree?',
        'faq.a3': 'Wir bieten flexible Preise basierend auf Ihrem Dokumentenvolumen, der Anzahl der Benutzer und den benötigten Funktionen. Kontaktieren Sie unser Vertriebsteam für ein individuelles Angebot, das zu Ihren Geschäftsanforderungen passt.',
        'faq.q4': 'Wie lange dauert die Implementierung?',
        'faq.a4': 'Die Implementierung dauert in der Regel 2-4 Wochen, abhängig von Ihren spezifischen Anforderungen und bestehenden Systemen. Wir bieten dedizierte Onboarding-Unterstützung und Schulungen, um einen reibungslosen Übergang zu gewährleisten.',
        'faq.q5': 'Kann ich ClerkTree in meine bestehenden Systeme integrieren?',
        'faq.a5': 'Ja! ClerkTree bietet REST-APIs und vorgefertigte Integrationen mit beliebten Business-Tools wie Salesforce, SAP, Microsoft Dynamics und mehr. Unser Team kann auch bei benutzerdefinierten Integrationen helfen.',

        // Footer
        'footer.product': 'Produkt',
        'footer.company': 'Unternehmen',
        'footer.contact': 'Kontakt',
        'footer.features': 'Funktionen',
        'footer.smartContracts': 'Smart Contracts',
        'footer.documents': 'Dokumente',
        'footer.aboutUs': 'Über uns',
        'footer.careers': 'Karriere',
        'footer.privacy': 'Datenschutzerklärung',
        'footer.terms': 'Nutzungsbedingungen',
        'footer.security': 'Sicherheit & Datenverarbeitung',
        'footer.rights': 'Alle Rechte vorbehalten.',
        'footer.legal': 'Rechtliches',
        'footer.docs': 'Dokumentation',
        'footer.phone': 'Telefon',
        'footer.linkedin': 'LinkedIn',
        'footer.cookiePolicy': 'Cookie-Richtlinie',

        // About Page
        'about.whyTitle': 'Warum wir ClerkTree gebaut haben',
        'about.whyDesc1': 'Wachsende Operationsteams stehen vor einer gemeinsamen Herausforderung: fragmentierte Arbeitsabläufe, die sie verlangsamen. Die Dokumentenverarbeitung ist über mehrere Tools verteilt, manuelle Dateneingabe kostet wertvolle Zeit und getrennte Systeme schaffen Engpässe.',
        'about.whyDesc2': 'Wir haben ClerkTree gebaut, um dieses Problem zu lösen. Unsere Plattform vereint KI-gesteuerte Automatisierung mit menschlicher Expertise und schafft einen nahtlosen Workflow, der die Durchlaufzeit um 40 % reduziert und gleichzeitig die Genauigkeit und das Urteilsvermögen beibehält, die nur Menschen bieten können.',
        'about.missionTitle': 'Unsere Mission',
        'about.missionDesc': 'Operationsteams mit intelligenter Automatisierung zu befähigen, die menschliche Fähigkeiten verstärkt und mühsame dokumentenlastige Prozesse in optimierte, effiziente Workflows verwandelt, die das Geschäftswachstum vorantreiben.',
        'about.visionTitle': 'Unsere Vision',
        'about.visionDesc': 'Das Betriebssystem für moderne Schadens- und Back-Office-Operationen zu werden, in dem KI und Menschen in perfekter Harmonie zusammenarbeiten, um beispiellose Geschwindigkeit, Genauigkeit und Kundenzufriedenheit zu liefern.',
        'about.hybridTitle': 'Der Hybride Mensch+KI Ansatz',
        'about.hybridDesc': 'Wir glauben, dass die Zukunft nicht darin liegt, Menschen durch KI zu ersetzen – sondern menschliche Intelligenz durch maschinelle Fähigkeiten zu erweitern. Unsere Plattform ist um diese Kernphilosophie herum aufgebaut:',
        'about.aiRepetition': 'KI übernimmt Wiederholungen',
        'about.aiRepetitionDesc': 'Automatisierte Dokumentenextraktion, Datenvalidierung und Routineverarbeitungsaufgaben',
        'about.humanComplexity': 'Menschen übernehmen Komplexität',
        'about.humanComplexityDesc': 'Komplexe Entscheidungsfindung, Grenzfälle und Kundeninteraktionen, die Empathie erfordern',
        'about.handoffs': 'Nahtlose Übergaben',
        'about.handoffsDesc': 'Intelligentes Routing zwischen KI und menschlichen Agenten basierend auf Aufgabenkomplexität und Vertrauensniveau',
        'about.industriesTitle': 'Branchen, die wir bedienen',
        'about.ind1': 'Versicherung',
        'about.ind2': 'BFSI',
        'about.ind3': 'BPO',
        'about.ind4': 'Operatives Geschäft',
        'about.ind5': 'Dokumentenverarbeitung',
        'about.joinTitle': 'Begleiten Sie uns auf dieser Reise',
        'about.joinDesc': 'Wir fangen gerade erst an. Arbeiten Sie mit uns zusammen, um Ihre Operationen zu transformieren.',
        'about.getInTouch': 'Kontakt aufnehmen',
        'about.joinTeam': 'Werden Sie Teil unseres Teams',
        'about.team.kenshin': 'Kenshin Kiriyama (COO) studiert Sustainable Management an der TUM. Zuvor war er im Vertrieb bei Affordables tätig und arbeitete mit Decathlon und der Sparkasse zusammen. Als Deutschlandstipendiat sorgt er nun bei ClerkTree für zuverlässigen Kundenservice und Wartung und entwickelt maßgeschneiderte Lösungen für komplexe Kundenanforderungen.',
        'about.team.animesh': 'Animesh Mishra (Gründer) studiert CS & ML am Shiv Nadar Institute of Eminence. Zuvor entwickelte er als Quant Research Analyst bei Consult Add Services Vorhersagemodelle. Bei ClerkTree konzentriert er sich nun auf Enterprise AI Orchestration und entwickelt autonome agentenbasierte Workflows zur Optimierung der Schadensbearbeitung und operativen Entscheidungsfindung.',
        'about.team.krishang': 'Krishang Sharma (AI Engineer) studiert CSE am Shiv Nadar Institute of Eminence und ist Absolvent des Arizona State University AI in Business Programms. Bei ClerkTree entwickelt er produktionsreife ML-, LLM- und RAG-Systeme. Zuvor trug er zu ML-Engineering und Forschung beim I4C (Innenministerium) und der Scientific Analysis Group, DRDO, bei.',
        'about.team.shobhit': 'Shobhit Mishra (CEO) studiert an der TUM mit Schwerpunkt auf nachhaltiger Datenautomatisierung. Zuvor arbeitete er an Automatisierungsprojekten bei Robotico. Bei ClerkTree leitet er nun die Entwicklung skalierbarer Lösungen und strategischer Prozesse, um Unternehmen bei der Optimierung komplexer digitaler Abläufe zu unterstützen.',
        'about.team.urja': 'Urja Shrestha (Customer Success Manager) studiert Sustainable Management and Technology an der TUM in Straubing, Bayern. Bei ClerkTree fördert sie die Kundenbindung durch Optimierung der Produktakzeptanz und maßgeschneiderte Strategien für eine nahtlose Integration. Ihr Fokus auf nachhaltige Systeme hilft Unternehmen, effiziente und langfristige betriebliche Abläufe aufzubauen.',
        'about.team.sinem': 'Sinem Koc (Legal Analyst) studiert Jura an der Johannes Gutenberg-Universität Mainz mit Schwerpunkt Life Science und Gesundheitsrecht und starken akademischen Ergebnissen. Bei ClerkTree arbeitet sie als Rechtsberaterin und unterstützt Compliance, Datenschutz und die rechtlichen Grundlagen, die für die Skalierung von KI-gesteuerten Geschäftslösungen erforderlich sind.',

        // Contact Page
        'contact.title1': 'Lassen Sie uns über',
        'contact.title2': 'Ihr Geschäft sprechen',
        'contact.subtitle': 'Kontaktieren Sie unser Team für Unternehmenslösungen und Support',
        'contact.phone': 'Telefon',
        'contact.location': 'Standort',
        'contact.sendMsgTitle': 'Senden Sie uns eine Nachricht',
        'contact.sendMsgDesc': 'Füllen Sie das untenstehende Formular aus und wir melden uns innerhalb von 1-2 Werktagen bei Ihnen.',
        'contact.successTitle': 'Nachricht gesendet!',
        'contact.successDesc': 'Vielen Dank für Ihre Kontaktaufnahme. Wir werden uns bald bei Ihnen melden!',
        'contact.fullName': 'Vollständiger Name',
        'contact.companyName': 'Firmenname',
        'contact.email': 'Geschäftliche E-Mail',
        'contact.phoneNumber': 'Telefonnummer',
        'contact.interest': 'Interesse',
        'contact.selectInterest': 'Wählen Sie Ihr Interesse...',
        'contact.intEnterprise': 'Unternehmenslizenz',
        'contact.intBulk': 'Großabnahme',
        'contact.intCustom': 'Individuelle Lösung',
        'contact.intOther': 'Sonstiges',
        'contact.employees': 'Anzahl der Mitarbeiter',
        'contact.selectRange': 'Bereich auswählen...',
        'contact.message': 'Nachricht',
        'contact.messagePlaceholder': 'Erzählen Sie uns von Ihren Bedürfnissen und Anforderungen...',
        'contact.error': 'Etwas ist schief gelaufen. Bitte versuchen Sie es später erneut.',
        'contact.sending': 'Senden...',
        'contact.sendButton': 'Nachricht senden',

        // Solutions Page
        'solutions.title1': 'Entwickelt für moderne',
        'solutions.title2': 'Schadensabläufe',
        'solutions.subtitle': 'Transformieren Sie Ihren Arbeitsablauf mit unternehmenstauglicher Automatisierung, angetrieben von modernster KI-Technologie.',
        'solutions.card1Title': 'KI-gestützte Dokumentenverarbeitung',
        'solutions.card1Desc': 'Automatisches Extrahieren, Klassifizieren und Validieren von Informationen aus Schadensdokumenten mithilfe fortschrittlicher Modelle des maschinellen Lernens.',
        'solutions.card1Feat1': 'OCR & Datenextraktion',
        'solutions.card1Feat2': 'Dokumentenklassifizierung',
        'solutions.card1Feat3': 'Auto-Validierung',
        'solutions.card2Title': 'Intelligente Workflow-Automatisierung',
        'solutions.card2Desc': 'Optimieren Sie Ihren Schadenprozess mit intelligentem Routing, automatisierter Entscheidungsfindung und nahtlosen Übergaben zwischen KI und menschlichen Agenten.',
        'solutions.card2Feat1': 'Intelligentes Aufgaben-Routing',
        'solutions.card2Feat2': 'Automatisierte Genehmigungen',
        'solutions.card2Feat3': 'Prozessoptimierung',
        'solutions.card3Title': 'Schadens-Triage & Priorisierung',
        'solutions.card3Desc': 'Automatisches Kategorisieren und Priorisieren eingehender Ansprüche basierend auf Dringlichkeit, Komplexität und potenziellen Betrugsindikatoren.',
        'solutions.card3Feat1': 'Dringlichkeitserkennung',
        'solutions.card3Feat2': 'Komplexitätsanalyse',
        'solutions.card3Feat3': 'Prioritätsbewertung',
        'solutions.card4Title': 'Echtzeit-Statusverfolgung',
        'solutions.card4Desc': 'Bieten Sie vollständige Transparenz über den Status von Ansprüchen mit automatischen Updates, Benachrichtigungen und umfassenden Audit-Trails.',
        'solutions.card4Feat1': 'Live-Status-Updates',
        'solutions.card4Feat2': 'Automatisierte Benachrichtigungen',
        'solutions.card4Feat3': 'Vollständiger Audit-Trail',
        'solutions.card5Title': 'Analysen & Berichte',
        'solutions.card5Desc': 'Gewinnen Sie umsetzbare Erkenntnisse mit umfassenden Dashboards, benutzerdefinierten Berichten und prädiktiven Analysen für eine bessere Entscheidungsfindung.',
        'solutions.card5Feat1': 'Benutzerdefinierte Dashboards',
        'solutions.card5Feat2': 'Prädiktive Analysen',
        'solutions.card5Feat3': 'Leistungskennzahlen',
        'solutions.card6Title': 'Compliance & Sicherheit',
        'solutions.card6Desc': 'Gewährleisten Sie die Einhaltung gesetzlicher Vorschriften mit integrierten Sicherheitsfunktionen, Audit-Protokollierung und automatisierten Compliance-Prüfungen.',
        'solutions.card6Feat1': 'Datenverschlüsselung',
        'solutions.card6Feat2': 'Compliance-Überwachung',
        'solutions.card6Feat3': 'Zugriffskontrollen',
        'solutions.ctaBadge': 'Starten Sie Ihre Reise',
        'solutions.ctaTitle1': 'Bereit, Ihre Abläufe',
        'solutions.ctaTitle2': 'zu transformieren?',
        'solutions.ctaDesc': 'Vereinbaren Sie eine personalisierte Demo, um zu sehen, wie unsere KI-gestützten Lösungen die Durchlaufzeit um',
        'solutions.ctaDescHighlight': '40%',
        'solutions.ctaDescEnd': 'reduzieren und die Genauigkeit drastisch verbessern können.',
        'solutions.bookDemo': 'Demo buchen',
        'solutions.contactSales': 'Vertrieb kontaktieren',

        // FAQ Page
        'faqPage.title1': 'Häufig gestellte',
        'faqPage.title2': 'Fragen',
        'faqPage.subtitle': 'Alles, was Sie über ClerkTree wissen müssen und wie wir Ihnen helfen können, Ihre Abläufe zu transformieren',
        'faqPage.catGeneral': 'Allgemein',
        'faqPage.catProduct': 'Produkt',
        'faqPage.catPricing': 'Preise',
        'faqPage.catSecurity': 'Sicherheit',
        'faqPage.catSupport': 'Support',
        'faqPage.q1': 'Was ist ClerkTree?',
        'faqPage.a1': 'ClerkTree ist eine KI-gestützte Workflow-Automatisierungsplattform für Schadens- und Back-Office-Operationen. Wir kombinieren menschliche Expertise mit künstlicher Intelligenz, um die Durchlaufzeit um 40 % zu reduzieren und gleichzeitig Genauigkeit und Qualität beizubehalten.',
        'faqPage.q2': 'Wie funktioniert der Mensch+KI-Ansatz?',
        'faqPage.a2': 'Unser hybrider Ansatz nutzt KI für repetitive Aufgaben wie Dokumentenextraktion und Datenvalidierung, während sich Menschen auf komplexe Entscheidungsfindung und Grenzfälle konzentrieren. Das System leitet Aufgaben intelligent zwischen KI und menschlichen Agenten basierend auf Komplexität und Vertrauensniveau weiter.',
        'faqPage.q3': 'Welche Branchen bedienen Sie?',
        'faqPage.a3': 'Wir bedienen hauptsächlich Versicherungen, BFSI (Banken, Finanzdienstleistungen und Versicherungen), BPO (Business Process Outsourcing), Operationsteams und Dokumentenverarbeitungssektoren. Unsere Plattform ist für dokumentenlastige Workflows und Schadensbearbeitung optimiert.',
        'faqPage.q4': 'Welche Art von Dokumenten kann ClerkTree verarbeiten?',
        'faqPage.a4': 'ClerkTree kann eine Vielzahl von Dokumenten verarbeiten, darunter Versicherungsansprüche, Rechnungen, Verträge, medizinische Unterlagen, Finanzberichte und andere geschäftliche Dokumente. Unsere KI ist darauf trainiert, relevante Informationen genau und effizient zu extrahieren.',
        'faqPage.q5': 'Wie lange dauert die Implementierung?',
        'faqPage.a5': 'Die Implementierung dauert in der Regel 2-4 Wochen, abhängig von Ihren spezifischen Anforderungen und bestehenden Systemen. Wir bieten dedizierte Onboarding-Unterstützung und Schulungen, um einen reibungslosen Übergang zu gewährleisten.',
        'faqPage.q6': 'Wie ist die Preisgestaltung von ClerkTree?',
        'faqPage.a6': 'Wir bieten flexible Preise basierend auf Ihrem Dokumentenvolumen, der Anzahl der Benutzer und den benötigten Funktionen. Kontaktieren Sie unser Vertriebsteam für ein individuelles Angebot, das zu Ihren Geschäftsanforderungen passt.',
        'faqPage.q7': 'Bieten Sie eine kostenlose Testphase an?',
        'faqPage.a7': 'Ja, wir bieten eine 14-tägige kostenlose Testphase für qualifizierte Unternehmen an. Während der Testphase haben Sie Zugriff auf unsere Kernfunktionen und engagierten Support, um die Plattform zu evaluieren.',
        'faqPage.q8': 'Ist meine Daten sicher bei ClerkTree?',
        'faqPage.a8': 'Absolut. Wir nehmen Sicherheit ernst, mit Ende-zu-Ende-Verschlüsselung, SOC 2-Konformität und regelmäßigen Sicherheitsaudits. Ihre Daten werden in einer sicheren, unternehmensfähigen Cloud-Infrastruktur mit mehreren Redundanzebenen gespeichert.',
        'faqPage.q9': 'Welche Compliance-Standards erfüllen Sie?',
        'faqPage.a9': 'ClerkTree erfüllt Industriestandards wie GDPR, HIPAA, SOC 2 Typ II und ISO 27001. Wir aktualisieren unsere Compliance-Maßnahmen kontinuierlich, um den sich entwickelnden regulatorischen Anforderungen gerecht zu werden.',
        'faqPage.q10': 'Welche Art von Support bieten Sie an?',
        'faqPage.a10': 'Wir bieten rund um die Uhr Kundensupport per E-Mail und Chat für alle Unternehmenskunden. Premium-Pläne umfassen dedizierte Account-Manager und telefonischen Support. Wir bieten auch umfassende Dokumentations- und Schulungsressourcen.',
        'faqPage.q11': 'Kann ich ClerkTree in meine bestehenden Systeme integrieren?',
        'faqPage.a11': 'Ja! ClerkTree bietet REST-APIs und vorgefertigte Integrationen mit beliebten Business-Tools wie Salesforce, SAP, Microsoft Dynamics und mehr. Unser Team kann auch bei benutzerdefinierten Integrationen helfen.',
        'faqPage.q12': 'Wie fange ich an?',
        'faqPage.a12': 'Der Einstieg ist einfach! Buchen Sie eine Demo, indem Sie uns eine E-Mail an team@clerktree.com senden, und wir vereinbaren einen persönlichen Durchgang. Danach helfen wir Ihnen, eine Testumgebung einzurichten, die auf Ihren spezifischen Anwendungsfall zugeschnitten ist.',
        'faqPage.stillQuestions': 'Haben Sie noch Fragen?',
        'faqPage.stillDesc': 'Unser Team ist hier, um zu helfen. Nehmen Sie Kontakt auf und wir beantworten alle Fragen, die Sie haben.',
        'faqPage.contactUs': 'Kontaktieren Sie uns',

        // Careers Page
        'careers.title1': 'Werden Sie Teil des',
        'careers.title2': 'ClerkTree-Teams',
        'careers.subtitle': 'Helfen Sie uns, den Betrieb mit KI-gestützter Automatisierung zu revolutionieren',
        'careers.linkedin': 'Suchen Sie nach neuen Jobs auf LinkedIn',
        'careers.or': 'ODER',
        'careers.formTitle': 'Reichen Sie Ihren Lebenslauf ein',
        'careers.formDesc': 'Füllen Sie das untenstehende Formular aus und wir melden uns innerhalb von 2-3 Werktagen bei Ihnen.',
        'careers.successTitle': 'Bewerbung abgeschickt!',
        'careers.successDesc': 'Wir werden Ihre Bewerbung prüfen und uns bald bei Ihnen melden.',
        'careers.fullName': 'Vollständiger Name',
        'careers.email': 'E-Mail-Adresse',
        'careers.phone': 'Telefonnummer',
        'careers.currentPos': 'Aktuelle Position',
        'careers.experience': 'Jahre Berufserfahrung',
        'careers.position': 'Gewünschte Position',
        'careers.select': 'Auswählen...',
        'careers.selectPos': 'Position auswählen...',
        'careers.pos1': 'Senior Frontend Engineer',
        'careers.pos2': 'Fullstack Engineer',
        'careers.pos3': 'Product Designer',
        'careers.other': 'Sonstiges',
        'careers.linkedinUrl': 'LinkedIn Profil-URL',
        'careers.portfolio': 'Portfolio/Website',
        'careers.coverLetter': 'Anschreiben / Warum möchten Sie zu ClerkTree?',
        'careers.resume': 'Lebenslauf',
        'careers.upload': 'Klicken Sie hier, um Ihren Lebenslauf hochzuladen (PDF, DOC, DOCX)',
        'careers.submit': 'Bewerbung absenden',
        'careers.submitting': 'Wird gesendet...',
        'careers.years': 'Jahre',

        // Blog
        'blog.all': 'Alle',
        'blog.selectCategory': 'Kategorie auswählen',

        // Header
        'header.notifications': 'Benachrichtigungen',
        'header.markAllRead': 'Alle als gelesen markieren',
        'header.noNotifications': 'Keine neuen Benachrichtigungen',

        'header.stayUpdated': 'Bleiben Sie über Ihre neuesten Aktivitäten auf dem Laufenden',

        // Sidebar
        'sidebar.platform': 'Plattform',
        'sidebar.aiBehavior': 'KI-Verhalten konfigurieren',
        'sidebar.groqAi': 'Groq KI',
        'sidebar.systemPrompt': 'System-Prompt',
        'sidebar.aiVoice': 'KI-Stimme',
        'sidebar.contextFields': 'Kontextfelder',
        'sidebar.categories': 'Kategorien',
        'sidebar.priorityRules': 'Prioritätsregeln',
        'sidebar.instructions': 'Anweisungen',
        'sidebar.saveConfig': 'Konfig. speichern',
        'sidebar.language': 'Sprache',

        // Invite Page
        'invite.support': 'Support',
        'invite.error': 'Ungültiger Einladungscode. Bitte versuchen Sie es erneut.',
        'invite.title': 'Zugang zur Plattform',
        'invite.subtitle': 'Geben Sie den Einladungscode Ihrer Organisation ein, um auf die Plattform zuzugreifen',
        'invite.placeholder': 'Einladungscode eingeben',
        'invite.continue': 'Weiter',
        'invite.requestAccess': 'Zugang anfordern',
        'invite.secure': 'Sichere Unternehmensverbindung',

        // Arbor Page & Chat
        'arbor.startTitle': 'Gespräch beginnen',
        'arbor.startDescAsk': 'Stellen Sie Fragen und erhalten Sie intelligente Antworten',
        'arbor.startDescTell': 'Führen Sie autonome Aufgaben und Aktionen aus',
        'arbor.startDescSearch': 'Durchsuchen Sie Ihre Dokumente',
        'arbor.placeholderAsk': 'Stellen Sie eine Frage zu Ihren Dokumenten...',
        'arbor.placeholderTell': 'Sagen Sie Arbor, was zu tun ist...',
        'arbor.placeholderSearch': 'Dokumente durchsuchen...',
        'arbor.viewDetails': 'Details anzeigen',
        'arbor.statusIndexing': 'Indizierung...',
        'arbor.statusIndexed': 'Indiziert (147 Dok.)',
        'arbor.filters': 'Filter',
        'arbor.reindex': 'Neu indizieren',
        'arbor.filterType': 'Nach Dokumenttyp filtern',
        'arbor.dateRange': 'Datumsbereich',
        'arbor.to': 'bis',
        'arbor.simulatedResponseAsk': 'Basierend auf den Informationen in Ihren Dokumenten habe ich Folgendes gefunden: Dies ist eine simulierte Antwort. In der Produktion würde dies eine Verbindung zur Arbor-Backend-API herstellen.',
        'arbor.simulatedResponseTell': 'Aufgabe erfolgreich ausgeführt. Dies ist eine simulierte Antwort. In der Produktion würde dies eine Verbindung zum Arbor-Backend herstellen und die angeforderte Aktion ausführen.',
        'arbor.simulatedResponseDoc': 'Relevante Dokumente gefunden, die Ihrer Anfrage entsprechen. Dies ist eine simulierte Antwort.',
        'arbor.send': 'Senden',
        'arbor.clear': 'Löschen',
        'arbor.modeAsk': 'Fragen',
        'arbor.modeTell': 'Befehlen',
        'arbor.modeSearch': 'Suchen',

        // Bioflow Page
        'bioflow.title': 'KI-Workflow-Designer',
        'bioflow.subtitle': 'Sehen Sie, wie KI Ihre Aufgaben automatisiert',
        'bioflow.poweredBy': 'Unterstützt von KI',
        'bioflow.smartAuto': 'Intelligente Automatisierung',
        'bioflow.realTime': 'Echtzeit',
        'bioflow.back': 'Zurück',
        'bioflow.tryIt': 'Probieren Sie es aus:',
        'bioflow.instruction': 'Wählen Sie oben einen Anwendungsfall aus und klicken Sie dann auf',
        'bioflow.runWorkflow': 'Workflow ausführen',
        'bioflow.inAction': 'um die KI in Aktion zu sehen',
        'bioflow.controls': 'Scrollen zum Schwenken • Klicken für Details • Zoomen mit Steuerelementen',

        // Blog Page
        'blogPage.title': 'Blog',
        'blogPage.subtitle': 'Neueste Nachrichten und Updates von ClerkTree.',
        'blogPage.loadingArticles': 'Artikel werden geladen...',
        'blogPage.loading': 'Wird geladen...',

        // Blog Post
        'blogPost.backToAll': 'Zurück zu allen Artikeln',
        'blogPost.related': 'Ähnliche Artikel',
        'blogPost.errorRendering': 'Fehler beim Rendern des Inhalts:',

        // Demo Dashboard
        'dashboard.title': 'Dashboard',
        'dashboard.subtitle': 'Dashboard',
        'dashboard.userView': 'Benutzeransicht',
        'dashboard.totalHistory': 'Gesamtverlauf',
        'dashboard.criticalHigh': 'Kritisch/Hoch',
        'dashboard.avgDuration': 'Ø Dauer',
        'dashboard.followUps': 'Wiedervorlagen',
        'dashboard.active': 'aktiv',
        'dashboard.allTime': 'Gesamtzeit',
        'dashboard.needAttention': 'Benötigen Aufmerksamkeit',
        'dashboard.perCall': 'Pro Anruf',
        'dashboard.pending': 'Ausstehend',
        'dashboard.priorityQueue': 'Prioritäts-Warteschlange',
        'dashboard.priority.critical': 'Kritisch',
        'dashboard.priority.high': 'Hohe Priorität',
        'dashboard.priority.medium': 'Mittel',
        'dashboard.priority.low': 'Niedrige Priorität',
        'dashboard.priority.highShort': 'Hoch',
        'dashboard.priority.mediumShort': 'Mittel',
        'dashboard.priority.lowShort': 'Niedrig',
        'dashboard.priority.noPending': 'Keine ausstehenden',
        'dashboard.priority.needFollowUp': 'erfordern Nachverfolgung',

        'dashboard.tab.monitor': 'Überwachung',
        'dashboard.tab.config': 'Konfiguration',
        'dashboard.tab.history': 'Verlauf',
        'dashboard.tab.monitorFull': 'Live-Monitor',
        'dashboard.tab.configFull': 'Wissensbasis',
        'dashboard.tab.historyFull': 'Verlauf',

        'dashboard.footer': 'ClerkTree KI-Dashboard',

        // Documents Page
        'documents.adminTitle': 'Admin Dokumentenprüfung',
        'documents.searchPlaceholder': 'Suche nach Ticket-ID oder Name...',
        'documents.statusAll': 'Status: Alle',
        'documents.priorityAll': 'Priorität: Alle',
        'documents.status.pending': 'Ausstehend',
        'documents.status.verified': 'Verifiziert',
        'documents.status.rejected': 'Abgelehnt',
        'documents.priority.high': 'Hoch',
        'documents.priority.medium': 'Mittel',
        'documents.priority.low': 'Niedrig',

        'documents.statistics': 'Statistiken',
        'documents.stats.pending': 'Ausstehende Prüfungen',
        'documents.stats.verified': 'Verifizierte Kunden',
        'documents.stats.progress': 'Prüfortschritt',
        'documents.stats.complete': 'Abgeschlossen',
        'documents.stats.clients': 'Kunden',

        'documents.quickActions': 'Schnellaktionen',
        'documents.exportReports': 'Berichte exportieren',

        'documents.ticket': 'Ticket:',
        'documents.type': 'Typ:',
        'documents.uploadedDocs': 'Hochgeladene Dokumente',

        'documents.blockchain.details': 'Blockchain-Details',
        'documents.blockchain.hash': 'Dokumenten-Hash:',
        'documents.blockchain.status': 'Status:',
        'documents.blockchain.uploader': 'Uploader:',
        'documents.blockchain.uploadTime': 'Upload-Zeit:',
        'documents.blockchain.verifier': 'Prüfer:',
        'documents.blockchain.verificationTime': 'Prüfzeit:',
        'documents.blockchain.verified': 'Verifiziert',
        'documents.blockchain.pending': 'Ausstehende Verifizierung',
        'documents.blockchain.refresh': 'Klicken Sie auf Aktualisieren, um Blockchain-Daten zu laden',

        'documents.preview.notAvailable': 'Vorschau nicht verfügbar für {ext} Dateien',

        'documents.modal.submissionDate': 'Einreichungsdatum',
        'documents.modal.status': 'Status',
        'documents.modal.preview': 'Dokumentenvorschau',
        'documents.modal.details': 'Dokumentendetails',
        'documents.modal.client': 'Kunde:',
        'documents.modal.ticketId': 'Ticket-ID:',
        'documents.modal.docType': 'Dokumententyp:',
        'documents.modal.history': 'Prüfverlauf',
        'documents.modal.noHistory': 'Kein Prüfverlauf verfügbar',

        // User Call & Chat
        'userCall.aiAssistant': 'Chat',
        'userCall.settings': 'Einstellungen',
        'chat.welcome': 'Wie kann ich Ihnen heute helfen?',
        'chat.startPrompt': 'Tippen Sie eine Nachricht oder starten Sie einen Anruf, um das Gespräch zu beginnen',
        'chat.thought': 'Gedacht für {time}s',
        'chat.listening': 'Zuhören...',
        'chat.placeholder.voice': 'Oder Nachricht eingeben...',
        'chat.placeholder.text': 'Geben Sie Ihre Nachricht ein...',
        'chat.end': 'Beenden',
        'chat.agentError': 'Entschuldigung, ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',

        // Juris Page & Chat
        'juris.caseConnection': 'Fallverbindungsanalyse',
        'juris.close': 'Schließen',
        'juris.selectedCase': 'Ausgewählter Fall',
        'juris.connectsToQuery': 'Wie es mit Ihrer Anfrage verbunden ist:',
        'juris.legalConcepts': 'Rechtskonzepte:',
        'juris.precedentChain': 'Präzedenzfallkette:',
        'juris.similarityScore': 'Ähnlichkeitsbewertung:',
        'juris.citedStatutes': 'Zitierte Gesetze:',
        'juris.retrievalTitle': 'Suche nach Rechtsfällen',
        'juris.descNormal': 'Schnelle semantische Suche mit KI-Embeddings',
        'juris.descDeep': 'Umfassende Analyse mit Zitiernetzwerken und Präzedenzfällen',
        'juris.detailNormal': 'Schnelle Ergebnisse durch Vektorähnlichkeit',
        'juris.detailDeep': 'Kombiniert semantische Suche, Wissensgraph und Zitate',
        'juris.foundSimilar': 'Ähnliche Fälle gefunden',
        'juris.aiAnalysis': 'KI-Analyse',
        'juris.summary': 'Zusammenfassung:',
        'juris.keyConcepts': 'Schlüsselkonzepte:',
        'juris.tryExamples': 'Versuchen Sie diese Beispiele:',
        'juris.placeholderNormal': 'Suchen Sie Fälle nach Rechtskonzepten, Fakten oder Beständen...',
        'juris.placeholderDeep': 'Stellen Sie komplexe Rechtsfragen, die eine tiefe Analyse erfordern...',
        'juris.placeholderClear': 'Chat löschen, um eine neue Suche zu starten...',
        'juris.modeNormal': 'Normal',
        'juris.modeDeep': 'Tiefensuche',
        'juris.simulatedDeep': "Basierend auf Ihrer detaillierten Anfrage habe ich eine umfassende Analyse der relevanten Rechtspräzedenzfälle und gesetzlichen Bestimmungen durchgeführt.\n\nDie Suche hat {count} hochsignifikante Fälle identifiziert, die sich direkt mit den von Ihnen aufgeworfenen rechtlichen Fragen befassen. Die Analyse deutet auf einen starken Präzedenztrend hin, der die Auslegung spezifischer gesetzlicher Klauseln im Einklang mit jüngsten Urteilen des Obersten Gerichtshofs begünstigt.\n\nWichtige Ergebnisse sind:\n1. Ein konsistenter gerichtlicher Ansatz zum Schutz der Grundrechte in ähnlichen Kontexten.\n2. Unterschiedliche Ansichten in Urteilen des High Court, die vom Apex Court beigelegt wurden.\n3. Spezifisches Vertrauen auf die Einhaltung von Verfahren als kritischer Faktor für den Ausgang des Verfahrens.\n\nUnten finden Sie die relevantesten Fälle mit detaillierten Zitiernetzwerken und Begründungsmustern für Ihre Überprüfung.",
        'juris.simulatedNormal': 'Ich habe {count} relevante Fälle für Ihre Situation gefunden. Diese Fälle decken ähnliche Szenarien ab und können Ihnen helfen, die potenziellen rechtlichen Ergebnisse zu verstehen.',

        // LiveCallMonitor
        'monitor.title': 'Live-Monitor',
        'monitor.status.active': 'Aktiv',
        'monitor.status.idle': 'Inaktiv',
        'monitor.apptDetails': 'Termindetails',
        'monitor.contactInfo': 'Kontaktinfo',
        'monitor.noContact': 'Kein Kontakt',
        'monitor.otherDetails': 'Andere Details',
        'monitor.category': 'Kategorie:',
        'monitor.noActive': 'Keine aktive Unterhaltung',
        'monitor.waiting': 'Warten auf Unterhaltung...',
        'monitor.startCall': 'Starten Sie einen Anruf, um das Transkript zu sehen',
        'monitor.recording': 'Aufzeichnung & Analyse...',
        'monitor.recordingShort': 'Aufzeichnung...',
        'monitor.followUp': 'Nachverfolgung erforderlich',

        // KnowledgeBase (Config)
        'config.title': 'Wissensbasis',
        'config.subtitle': 'KI-Verhalten konfigurieren',
        'config.save': 'Konfig. speichern',
        'config.saved': 'Gespeichert!',
        'config.systemPrompt': 'System-Prompt',
        'config.systemPromptDesc': 'Definieren Sie das Kernverhalten und die Persönlichkeit der KI...',
        'config.persona': 'KI-Persona',
        'config.personaPlaceholder': 'z.B. Professioneller, empathischer Assistent',
        'config.greeting': 'Begrüßung',
        'config.greetingPlaceholder': 'Wie die KI Anrufer begrüßt...',
        'config.guidelines': 'Antwortrichtlinien',
        'config.guidelinesPlaceholder': 'Richtlinien, wie die KI antworten soll...',
        'config.voice': 'KI-Stimme',
        'config.fields': 'Kontextfelder',
        'config.fieldsDesc': 'Definieren Sie Felder, die die KI aus Gesprächen extrahieren soll',
        'config.categories': 'Kategorien',
        'config.categoriesDesc': 'Kategorien zur Anrufklassifizierung',
        'config.rules': 'Prioritätsregeln',
        'config.instructions': 'Anweisungen',
        'config.addField': 'Feld hinzufügen',
        'config.addCategory': 'Kategorie hinzufügen',
        'config.fieldName': 'Feldname',
        'config.fieldDesc': 'Beschreibung (optional)',
        'config.required': 'Pflichtfeld',
        'config.cancel': 'Abbrechen',
        'config.add': 'Hinzufügen',
        'config.catName': 'Kategoriename',
        'config.catDesc': 'Beschreibung',
        'config.groqConnected': 'Groq KI',
        'config.groqOffline': 'Offline',

        // CallHistory
        'history.title': 'Verlauf',
        'history.stats': '{count} von {total} Elementen • {voice} Anrufe, {text} Chats',
        'history.justNow': 'Gerade eben',
        'history.ago.h': 'vor {h} Std.',
        'history.ago.d': 'vor {d} Tagen',
        'history.duration': '{m}m {s}s',
        'history.noHistory': 'Kein Verlauf gefunden',
        'history.noHistoryDesc': 'Anruf- und Chatverlauf erscheint hier',
        'history.adjustFilters': 'Versuchen Sie, Ihre Filter anzupassen',
        'history.filter.allTypes': 'Alle Typen',
        'history.filter.calls': 'Nur Anrufe',
        'history.filter.chats': 'Nur Chats',
        'history.filter.allPriorities': 'Alle Prioritäten',
        'history.filter.allCategories': 'Alle Kategorien',
        'history.type.call': 'Anruf',
        'history.type.chat': 'Chat',
        'history.intent': 'Anrufer-Absicht',
        'history.sentiment': 'Stimmung',
        'history.priority': 'Priorität',
        'history.resolution': 'Lösung',
        'history.riskLevel': 'Risikostufe',
        'history.noTranscript': 'Kein Transkript verfügbar',
        'history.keyPoints': 'Wichtige Punkte',
        'history.topics': 'Themen',
        'history.mood': 'Stimmungsindikatoren',
        'history.suggestions': 'KI-Vorschläge für Admin',
        'history.actionItems': 'Aktionselemente',
        'history.extractedInfo': 'Extrahierte Informationen',
        'history.tags': 'Tags',

        // Active Sessions Panel
        'dashboard.activeSessions': 'Aktive Sitzungen',
        'dashboard.voiceCalls': 'Sprachanrufe',
        'dashboard.textChats': 'Text-Chats',
        'dashboard.inProgress': 'Läuft',
        'dashboard.noActive': 'Keine aktiven Sitzungen',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app-language') as Language;
        if (savedLang === 'en' || savedLang === 'de') {
            setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app-language', lang);
        window.dispatchEvent(new CustomEvent('language-change', { detail: lang }));
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
