// Auto-generated voice configuration
// DO NOT EDIT - Generated by upload_to_supabase.py

export interface VoiceConfig {
  id: string;
  name: string;
  gender: 'male' | 'female';
  accent: 'American' | 'British';
  description: string;
  sampleUrl: string;
}

export const AVAILABLE_VOICES: VoiceConfig[] = [
  {
    id: "af_nova",
    name: "Nova",
    gender: "female",
    accent: "American",
    description: "Default female voice - clear and professional",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_af_nova.wav",
  },
  {
    id: "af_sky",
    name: "Sky",
    gender: "female",
    accent: "American",
    description: "Bright and friendly female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_af_sky.wav",
  },
  {
    id: "af_bella",
    name: "Bella",
    gender: "female",
    accent: "American",
    description: "Warm and conversational female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_af_bella.wav",
  },
  {
    id: "af_nicole",
    name: "Nicole",
    gender: "female",
    accent: "American",
    description: "Calm and reassuring female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_af_nicole.wav",
  },
  {
    id: "af_sarah",
    name: "Sarah",
    gender: "female",
    accent: "American",
    description: "Energetic and upbeat female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_af_sarah.wav",
  },
  {
    id: "bf_emma",
    name: "Emma",
    gender: "female",
    accent: "British",
    description: "Sophisticated British female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_bf_emma.wav",
  },
  {
    id: "bf_isabella",
    name: "Isabella",
    gender: "female",
    accent: "British",
    description: "Elegant British female voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_bf_isabella.wav",
  },
  {
    id: "am_adam",
    name: "Adam",
    gender: "male",
    accent: "American",
    description: "Default male voice - authoritative and clear",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_am_adam.wav",
  },
  {
    id: "am_michael",
    name: "Michael",
    gender: "male",
    accent: "American",
    description: "Deep and professional male voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_am_michael.wav",
  },
  {
    id: "bm_george",
    name: "George",
    gender: "male",
    accent: "British",
    description: "Distinguished British male voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_bm_george.wav",
  },
  {
    id: "bm_lewis",
    name: "Lewis",
    gender: "male",
    accent: "British",
    description: "Friendly British male voice",
    sampleUrl: "https://xlzwfkgurrrspcdyqele.supabase.co/storage/v1/object/public/voice-samples/voice_bm_lewis.wav",
  },
];

export const DEFAULT_VOICE = "af_nova";
export const DEFAULT_VOICE_ID = "af_nova";

// Supabase storage bucket for voice samples
export const VOICE_SAMPLES_BUCKET = 'voice-samples';

// Helper functions
export const getVoiceById = (id: string): VoiceConfig | undefined => {
  return AVAILABLE_VOICES.find(v => v.id === id);
};

export const getVoicesByGender = (gender: 'male' | 'female'): VoiceConfig[] => {
  return AVAILABLE_VOICES.filter(v => v.gender === gender);
};

export const getVoicesByAccent = (accent: 'American' | 'British'): VoiceConfig[] => {
  return AVAILABLE_VOICES.filter(v => v.accent === accent);
};

// Get the sample audio URL for a voice
export const getVoiceSampleUrl = (voiceId: string, supabaseUrl: string): string => {
  return `${supabaseUrl}/storage/v1/object/public/${VOICE_SAMPLES_BUCKET}/voice_${voiceId}.wav`;
};
