export type Role = {
  role: string;
  group: string;
  accessLevel: string;
  users: number;
  permissionSets: string[];
  lastReview: string;
  owner: string;
  status: "Active" | "Needs review";
};

export const roles: Role[] = [
  {
    role: "TV",
    group: "Needs review",
    accessLevel: "Scoped",
    users: 3,
    permissionSets: ["Angebote erstellen", "Kalkulation", "Kundendaten", "Reports"],
    lastReview: "Apr 12, 2026",
    owner: "System",
    status: "Needs review",
  },
  {
    role: "PM",
    group: "Needs review",
    accessLevel: "Full",
    users: 3,
    permissionSets: ["Angebote freigeben", "Kalkulation", "Kundendaten", "Reports", "Bestellungen"],
    lastReview: "Apr 15, 2026",
    owner: "Sabine Ecker",
    status: "Needs review",
  },
  {
    role: "AL",
    group: "Needs review",
    accessLevel: "Scoped",
    users: 4,
    permissionSets: ["Auftrag anlegen", "Bestellungen", "AB erstellen", "Lieferungen"],
    lastReview: "Apr 18, 2026",
    owner: "Sabine Ecker",
    status: "Needs review",
  },
  {
    role: "PTL",
    group: "System roles",
    accessLevel: "Scoped",
    users: 3,
    permissionSets: ["Technisches Kickoff", "Kostencheck", "Dokumente", "Freigaben"],
    lastReview: "May 1, 2026",
    owner: "System",
    status: "Active",
  },
  {
    role: "Kostencheck-Analyst",
    group: "System roles",
    accessLevel: "Scoped",
    users: 3,
    permissionSets: ["Kostencheck", "Abweichungen", "Dashboards", "Exports"],
    lastReview: "May 5, 2026",
    owner: "System",
    status: "Active",
  },
  {
    role: "Kunde",
    group: "System roles",
    accessLevel: "Read only",
    users: 1,
    permissionSets: ["Projektstatus", "Dokumente"],
    lastReview: "May 6, 2026",
    owner: "System",
    status: "Active",
  },
  {
    role: "Service",
    group: "System roles",
    accessLevel: "API access",
    users: 2,
    permissionSets: ["Integrations", "API Keys", "Webhooks", "Logs"],
    lastReview: "Apr 22, 2026",
    owner: "System",
    status: "Active",
  },
  {
    role: "Finanzen",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 2,
    permissionSets: ["Billing", "Rechnungen", "Zahlungen", "Reports"],
    lastReview: "Apr 28, 2026",
    owner: "Bianca Hofmann",
    status: "Active",
  },
  {
    role: "Einkauf",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 2,
    permissionSets: ["Bestellungen", "Lieferanten", "Reports", "Exports"],
    lastReview: "May 2, 2026",
    owner: "Nadine Weiss",
    status: "Active",
  },
  {
    role: "Compliance",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 3,
    permissionSets: ["Audit Logs", "Freigaben", "Settings", "Reports"],
    lastReview: "May 3, 2026",
    owner: "Katrin Sommer",
    status: "Active",
  },
  {
    role: "Projektleiter Technik (Senior)",
    group: "Custom roles",
    accessLevel: "Scoped",
    users: 2,
    permissionSets: ["Projekte", "Kostencheck", "Reports", "Freigaben", "Settings"],
    lastReview: "Apr 30, 2026",
    owner: "Claudia Reinhardt",
    status: "Active",
  },
  {
    role: "Finance Viewer",
    group: "Custom roles",
    accessLevel: "Read only",
    users: 2,
    permissionSets: ["Billing", "Reports", "Rechnungen", "Dashboards"],
    lastReview: "May 7, 2026",
    owner: "Bianca Hofmann",
    status: "Active",
  },
];
