"""Document parsing: digital-PDF text/table extraction with an OCR fallback.

Deliberately CPU-only. pdfplumber handles the vast majority of Angebot/
Bestellung PDFs (they're generated by ERP/office software, not scanned).
Tesseract only kicks in when a page yields near-zero extractable text,
which is the signature of a scanned/flattened page.
"""

from __future__ import annotations

import pdfplumber


def extract_text(file_path: str) -> str:
    pages_text: list[str] = []
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text() or ""
            if len(text.strip()) < 20:
                text = _ocr_page(page)
            pages_text.append(text)
            for table in page.extract_tables() or []:
                pages_text.append(_table_to_text(table))
    return "\n\n".join(pages_text)


def _table_to_text(table: list[list[str | None]]) -> str:
    rows = [" | ".join(cell or "" for cell in row) for row in table]
    return "\n".join(rows)


def _ocr_page(page) -> str:
    try:
        import pytesseract
    except ImportError:
        return ""

    image = page.to_image(resolution=300).original
    return pytesseract.image_to_string(image, lang="deu+eng")
